// <copyright file="OverlordCardEventArgsTest.ToString01.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Descent.Messaging.Events
{
    public partial class OverlordCardEventArgsTest
    {
[TestMethod]
[PexGeneratedBy(typeof(OverlordCardEventArgsTest))]
public void ToString01919()
{
    OverlordCardEventArgs overlordCardEventArgs;
    string s;
    overlordCardEventArgs = new OverlordCardEventArgs(1);
    ((GameEventArgs)overlordCardEventArgs).SenderId = 0;
    ((GameEventArgs)overlordCardEventArgs).EventId = (string)null;
    ((GameEventArgs)overlordCardEventArgs).EventType = (EventType)0;
    ((GameEventArgs)overlordCardEventArgs).NeedResponse = false;
    s = this.ToString01(overlordCardEventArgs);
    Assert.AreEqual<string>("1", s);
    Assert.IsNotNull((object)overlordCardEventArgs);
    Assert.AreEqual<int>(1, overlordCardEventArgs.OverlordCardId);
    Assert.AreEqual<int>(0, ((GameEventArgs)overlordCardEventArgs).SenderId);
    Assert.AreEqual<string>
        ((string)null, ((GameEventArgs)overlordCardEventArgs).EventId);
    Assert.AreEqual<EventType>
        ((EventType)0, ((GameEventArgs)overlordCardEventArgs).EventType);
    Assert.AreEqual<bool>
        (false, ((GameEventArgs)overlordCardEventArgs).NeedResponse);
}
    }
}
