// <copyright file="OverlordCardEventArgsTest.PopulateWithArgs.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;

namespace Descent.Messaging.Events
{
    public partial class OverlordCardEventArgsTest
    {
[TestMethod]
[PexGeneratedBy(typeof(OverlordCardEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException754()
{
    try
    {
      OverlordCardEventArgs overlordCardEventArgs;
      overlordCardEventArgs = new OverlordCardEventArgs(1);
      ((GameEventArgs)overlordCardEventArgs).SenderId = 0;
      ((GameEventArgs)overlordCardEventArgs).EventId = (string)null;
      ((GameEventArgs)overlordCardEventArgs).EventType = (EventType)0;
      ((GameEventArgs)overlordCardEventArgs).NeedResponse = false;
      string[] ss = new string[1];
      ss[0] = "-00:";
      this.PopulateWithArgs(overlordCardEventArgs, ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(OverlordCardEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException100()
{
    try
    {
      OverlordCardEventArgs overlordCardEventArgs;
      overlordCardEventArgs = new OverlordCardEventArgs(1);
      ((GameEventArgs)overlordCardEventArgs).SenderId = 0;
      ((GameEventArgs)overlordCardEventArgs).EventId = (string)null;
      ((GameEventArgs)overlordCardEventArgs).EventType = (EventType)0;
      ((GameEventArgs)overlordCardEventArgs).NeedResponse = false;
      string[] ss = new string[1];
      ss[0] = "-0:";
      this.PopulateWithArgs(overlordCardEventArgs, ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(OverlordCardEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException857()
{
    try
    {
      OverlordCardEventArgs overlordCardEventArgs;
      overlordCardEventArgs = new OverlordCardEventArgs(1);
      ((GameEventArgs)overlordCardEventArgs).SenderId = 0;
      ((GameEventArgs)overlordCardEventArgs).EventId = (string)null;
      ((GameEventArgs)overlordCardEventArgs).EventType = (EventType)0;
      ((GameEventArgs)overlordCardEventArgs).NeedResponse = false;
      string[] ss = new string[1];
      ss[0] = "-\0";
      this.PopulateWithArgs(overlordCardEventArgs, ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(OverlordCardEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException231()
{
    try
    {
      OverlordCardEventArgs overlordCardEventArgs;
      overlordCardEventArgs = new OverlordCardEventArgs(1);
      ((GameEventArgs)overlordCardEventArgs).SenderId = 0;
      ((GameEventArgs)overlordCardEventArgs).EventId = (string)null;
      ((GameEventArgs)overlordCardEventArgs).EventType = (EventType)0;
      ((GameEventArgs)overlordCardEventArgs).NeedResponse = false;
      string[] ss = new string[1];
      ss[0] = "-";
      this.PopulateWithArgs(overlordCardEventArgs, ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(OverlordCardEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException969()
{
    try
    {
      OverlordCardEventArgs overlordCardEventArgs;
      overlordCardEventArgs = new OverlordCardEventArgs(1);
      ((GameEventArgs)overlordCardEventArgs).SenderId = 0;
      ((GameEventArgs)overlordCardEventArgs).EventId = (string)null;
      ((GameEventArgs)overlordCardEventArgs).EventType = (EventType)0;
      ((GameEventArgs)overlordCardEventArgs).NeedResponse = false;
      string[] ss = new string[1];
      ss[0] = ":";
      this.PopulateWithArgs(overlordCardEventArgs, ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(OverlordCardEventArgsTest))]
public void PopulateWithArgs767()
{
    OverlordCardEventArgs overlordCardEventArgs;
    overlordCardEventArgs = new OverlordCardEventArgs(1);
    ((GameEventArgs)overlordCardEventArgs).SenderId = 0;
    ((GameEventArgs)overlordCardEventArgs).EventId = (string)null;
    ((GameEventArgs)overlordCardEventArgs).EventType = (EventType)0;
    ((GameEventArgs)overlordCardEventArgs).NeedResponse = false;
    string[] ss = new string[1];
    ss[0] = "0";
    this.PopulateWithArgs(overlordCardEventArgs, ss);
    Assert.IsNotNull((object)overlordCardEventArgs);
    Assert.AreEqual<int>(0, overlordCardEventArgs.OverlordCardId);
    Assert.AreEqual<int>(0, ((GameEventArgs)overlordCardEventArgs).SenderId);
    Assert.AreEqual<string>
        ((string)null, ((GameEventArgs)overlordCardEventArgs).EventId);
    Assert.AreEqual<EventType>
        ((EventType)0, ((GameEventArgs)overlordCardEventArgs).EventType);
    Assert.AreEqual<bool>
        (false, ((GameEventArgs)overlordCardEventArgs).NeedResponse);
}
[TestMethod]
[PexGeneratedBy(typeof(OverlordCardEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException765()
{
    try
    {
      OverlordCardEventArgs overlordCardEventArgs;
      overlordCardEventArgs = new OverlordCardEventArgs(1);
      ((GameEventArgs)overlordCardEventArgs).SenderId = 0;
      ((GameEventArgs)overlordCardEventArgs).EventId = (string)null;
      ((GameEventArgs)overlordCardEventArgs).EventType = (EventType)0;
      ((GameEventArgs)overlordCardEventArgs).NeedResponse = false;
      string[] ss = new string[1];
      ss[0] = "\0";
      this.PopulateWithArgs(overlordCardEventArgs, ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(OverlordCardEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException895()
{
    try
    {
      OverlordCardEventArgs overlordCardEventArgs;
      overlordCardEventArgs = new OverlordCardEventArgs(1);
      ((GameEventArgs)overlordCardEventArgs).SenderId = 0;
      ((GameEventArgs)overlordCardEventArgs).EventId = (string)null;
      ((GameEventArgs)overlordCardEventArgs).EventType = (EventType)0;
      ((GameEventArgs)overlordCardEventArgs).NeedResponse = false;
      string[] ss = new string[1];
      ss[0] = "";
      this.PopulateWithArgs(overlordCardEventArgs, ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(OverlordCardEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException24()
{
    try
    {
      OverlordCardEventArgs overlordCardEventArgs;
      overlordCardEventArgs = new OverlordCardEventArgs(1);
      ((GameEventArgs)overlordCardEventArgs).SenderId = 0;
      ((GameEventArgs)overlordCardEventArgs).EventId = (string)null;
      ((GameEventArgs)overlordCardEventArgs).EventType = (EventType)0;
      ((GameEventArgs)overlordCardEventArgs).NeedResponse = false;
      string[] ss = new string[1];
      this.PopulateWithArgs(overlordCardEventArgs, ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(OverlordCardEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException51()
{
    try
    {
      OverlordCardEventArgs overlordCardEventArgs;
      overlordCardEventArgs = new OverlordCardEventArgs(1);
      ((GameEventArgs)overlordCardEventArgs).SenderId = 0;
      ((GameEventArgs)overlordCardEventArgs).EventId = (string)null;
      ((GameEventArgs)overlordCardEventArgs).EventType = (EventType)0;
      ((GameEventArgs)overlordCardEventArgs).NeedResponse = false;
      string[] ss = new string[0];
      this.PopulateWithArgs(overlordCardEventArgs, ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(OverlordCardEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException259()
{
    try
    {
      OverlordCardEventArgs overlordCardEventArgs;
      overlordCardEventArgs = new OverlordCardEventArgs(1);
      ((GameEventArgs)overlordCardEventArgs).SenderId = 0;
      ((GameEventArgs)overlordCardEventArgs).EventId = (string)null;
      ((GameEventArgs)overlordCardEventArgs).EventType = (EventType)0;
      ((GameEventArgs)overlordCardEventArgs).NeedResponse = false;
      this.PopulateWithArgs(overlordCardEventArgs, (string[])null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
    }
}
