// <copyright file="RequestBuyEquipmentEventArgsTest.PopulateWithArgs.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;

namespace Descent.Messaging.Events
{
    public partial class RequestBuyEquipmentEventArgsTest
    {
[TestMethod]
[PexGeneratedBy(typeof(RequestBuyEquipmentEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException633()
{
    try
    {
      RequestBuyEquipmentEventArgs requestBuyEquipmentEventArgs;
      requestBuyEquipmentEventArgs = new RequestBuyEquipmentEventArgs(1);
      ((GameEventArgs)requestBuyEquipmentEventArgs).SenderId = 0;
      ((GameEventArgs)requestBuyEquipmentEventArgs).EventId = (string)null;
      ((GameEventArgs)requestBuyEquipmentEventArgs).EventType = (EventType)0;
      ((GameEventArgs)requestBuyEquipmentEventArgs).NeedResponse = false;
      string[] ss = new string[1];
      ss[0] = "-00:";
      this.PopulateWithArgs(requestBuyEquipmentEventArgs, ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(RequestBuyEquipmentEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException878()
{
    try
    {
      RequestBuyEquipmentEventArgs requestBuyEquipmentEventArgs;
      requestBuyEquipmentEventArgs = new RequestBuyEquipmentEventArgs(1);
      ((GameEventArgs)requestBuyEquipmentEventArgs).SenderId = 0;
      ((GameEventArgs)requestBuyEquipmentEventArgs).EventId = (string)null;
      ((GameEventArgs)requestBuyEquipmentEventArgs).EventType = (EventType)0;
      ((GameEventArgs)requestBuyEquipmentEventArgs).NeedResponse = false;
      string[] ss = new string[1];
      ss[0] = "-0:";
      this.PopulateWithArgs(requestBuyEquipmentEventArgs, ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(RequestBuyEquipmentEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException729()
{
    try
    {
      RequestBuyEquipmentEventArgs requestBuyEquipmentEventArgs;
      requestBuyEquipmentEventArgs = new RequestBuyEquipmentEventArgs(1);
      ((GameEventArgs)requestBuyEquipmentEventArgs).SenderId = 0;
      ((GameEventArgs)requestBuyEquipmentEventArgs).EventId = (string)null;
      ((GameEventArgs)requestBuyEquipmentEventArgs).EventType = (EventType)0;
      ((GameEventArgs)requestBuyEquipmentEventArgs).NeedResponse = false;
      string[] ss = new string[1];
      ss[0] = "-\0";
      this.PopulateWithArgs(requestBuyEquipmentEventArgs, ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(RequestBuyEquipmentEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException712()
{
    try
    {
      RequestBuyEquipmentEventArgs requestBuyEquipmentEventArgs;
      requestBuyEquipmentEventArgs = new RequestBuyEquipmentEventArgs(1);
      ((GameEventArgs)requestBuyEquipmentEventArgs).SenderId = 0;
      ((GameEventArgs)requestBuyEquipmentEventArgs).EventId = (string)null;
      ((GameEventArgs)requestBuyEquipmentEventArgs).EventType = (EventType)0;
      ((GameEventArgs)requestBuyEquipmentEventArgs).NeedResponse = false;
      string[] ss = new string[1];
      ss[0] = "-";
      this.PopulateWithArgs(requestBuyEquipmentEventArgs, ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(RequestBuyEquipmentEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException7()
{
    try
    {
      RequestBuyEquipmentEventArgs requestBuyEquipmentEventArgs;
      requestBuyEquipmentEventArgs = new RequestBuyEquipmentEventArgs(1);
      ((GameEventArgs)requestBuyEquipmentEventArgs).SenderId = 0;
      ((GameEventArgs)requestBuyEquipmentEventArgs).EventId = (string)null;
      ((GameEventArgs)requestBuyEquipmentEventArgs).EventType = (EventType)0;
      ((GameEventArgs)requestBuyEquipmentEventArgs).NeedResponse = false;
      string[] ss = new string[1];
      ss[0] = ":";
      this.PopulateWithArgs(requestBuyEquipmentEventArgs, ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(RequestBuyEquipmentEventArgsTest))]
public void PopulateWithArgs968()
{
    RequestBuyEquipmentEventArgs requestBuyEquipmentEventArgs;
    requestBuyEquipmentEventArgs = new RequestBuyEquipmentEventArgs(1);
    ((GameEventArgs)requestBuyEquipmentEventArgs).SenderId = 0;
    ((GameEventArgs)requestBuyEquipmentEventArgs).EventId = (string)null;
    ((GameEventArgs)requestBuyEquipmentEventArgs).EventType = (EventType)0;
    ((GameEventArgs)requestBuyEquipmentEventArgs).NeedResponse = false;
    string[] ss = new string[1];
    ss[0] = "0";
    this.PopulateWithArgs(requestBuyEquipmentEventArgs, ss);
    Assert.IsNotNull((object)requestBuyEquipmentEventArgs);
    Assert.AreEqual<int>(0, requestBuyEquipmentEventArgs.EquipmentId);
    Assert.AreEqual<int>(0, ((GameEventArgs)requestBuyEquipmentEventArgs).SenderId);
    Assert.AreEqual<string>
        ((string)null, ((GameEventArgs)requestBuyEquipmentEventArgs).EventId);
    Assert.AreEqual<EventType>
        ((EventType)0, ((GameEventArgs)requestBuyEquipmentEventArgs).EventType);
    Assert.AreEqual<bool>
        (false, ((GameEventArgs)requestBuyEquipmentEventArgs).NeedResponse);
}
[TestMethod]
[PexGeneratedBy(typeof(RequestBuyEquipmentEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException413()
{
    try
    {
      RequestBuyEquipmentEventArgs requestBuyEquipmentEventArgs;
      requestBuyEquipmentEventArgs = new RequestBuyEquipmentEventArgs(1);
      ((GameEventArgs)requestBuyEquipmentEventArgs).SenderId = 0;
      ((GameEventArgs)requestBuyEquipmentEventArgs).EventId = (string)null;
      ((GameEventArgs)requestBuyEquipmentEventArgs).EventType = (EventType)0;
      ((GameEventArgs)requestBuyEquipmentEventArgs).NeedResponse = false;
      string[] ss = new string[1];
      ss[0] = "\0";
      this.PopulateWithArgs(requestBuyEquipmentEventArgs, ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(RequestBuyEquipmentEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException770()
{
    try
    {
      RequestBuyEquipmentEventArgs requestBuyEquipmentEventArgs;
      requestBuyEquipmentEventArgs = new RequestBuyEquipmentEventArgs(1);
      ((GameEventArgs)requestBuyEquipmentEventArgs).SenderId = 0;
      ((GameEventArgs)requestBuyEquipmentEventArgs).EventId = (string)null;
      ((GameEventArgs)requestBuyEquipmentEventArgs).EventType = (EventType)0;
      ((GameEventArgs)requestBuyEquipmentEventArgs).NeedResponse = false;
      string[] ss = new string[1];
      ss[0] = "";
      this.PopulateWithArgs(requestBuyEquipmentEventArgs, ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(RequestBuyEquipmentEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException320()
{
    try
    {
      RequestBuyEquipmentEventArgs requestBuyEquipmentEventArgs;
      requestBuyEquipmentEventArgs = new RequestBuyEquipmentEventArgs(1);
      ((GameEventArgs)requestBuyEquipmentEventArgs).SenderId = 0;
      ((GameEventArgs)requestBuyEquipmentEventArgs).EventId = (string)null;
      ((GameEventArgs)requestBuyEquipmentEventArgs).EventType = (EventType)0;
      ((GameEventArgs)requestBuyEquipmentEventArgs).NeedResponse = false;
      string[] ss = new string[1];
      this.PopulateWithArgs(requestBuyEquipmentEventArgs, ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(RequestBuyEquipmentEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException446()
{
    try
    {
      RequestBuyEquipmentEventArgs requestBuyEquipmentEventArgs;
      requestBuyEquipmentEventArgs = new RequestBuyEquipmentEventArgs(1);
      ((GameEventArgs)requestBuyEquipmentEventArgs).SenderId = 0;
      ((GameEventArgs)requestBuyEquipmentEventArgs).EventId = (string)null;
      ((GameEventArgs)requestBuyEquipmentEventArgs).EventType = (EventType)0;
      ((GameEventArgs)requestBuyEquipmentEventArgs).NeedResponse = false;
      string[] ss = new string[0];
      this.PopulateWithArgs(requestBuyEquipmentEventArgs, ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(RequestBuyEquipmentEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException224()
{
    try
    {
      RequestBuyEquipmentEventArgs requestBuyEquipmentEventArgs;
      requestBuyEquipmentEventArgs = new RequestBuyEquipmentEventArgs(1);
      ((GameEventArgs)requestBuyEquipmentEventArgs).SenderId = 0;
      ((GameEventArgs)requestBuyEquipmentEventArgs).EventId = (string)null;
      ((GameEventArgs)requestBuyEquipmentEventArgs).EventType = (EventType)0;
      ((GameEventArgs)requestBuyEquipmentEventArgs).NeedResponse = false;
      this.PopulateWithArgs(requestBuyEquipmentEventArgs, (string[])null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
    }
}
