// <copyright file="SurgeAbilityEventArgsTest.ToString01.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Descent.Messaging.Events
{
    public partial class SurgeAbilityEventArgsTest
    {
[TestMethod]
[PexGeneratedBy(typeof(SurgeAbilityEventArgsTest))]
public void ToString01880()
{
    SurgeAbilityEventArgs surgeAbilityEventArgs;
    string s;
    surgeAbilityEventArgs = new SurgeAbilityEventArgs(2);
    ((GameEventArgs)surgeAbilityEventArgs).SenderId = 0;
    ((GameEventArgs)surgeAbilityEventArgs).EventId = (string)null;
    ((GameEventArgs)surgeAbilityEventArgs).EventType = (EventType)0;
    ((GameEventArgs)surgeAbilityEventArgs).NeedResponse = false;
    s = this.ToString01(surgeAbilityEventArgs);
    Assert.AreEqual<string>("2", s);
    Assert.IsNotNull((object)surgeAbilityEventArgs);
    Assert.AreEqual<int>(2, surgeAbilityEventArgs.AbilityId);
    Assert.AreEqual<int>(0, ((GameEventArgs)surgeAbilityEventArgs).SenderId);
    Assert.AreEqual<string>
        ((string)null, ((GameEventArgs)surgeAbilityEventArgs).EventId);
    Assert.AreEqual<EventType>
        ((EventType)0, ((GameEventArgs)surgeAbilityEventArgs).EventType);
    Assert.AreEqual<bool>
        (false, ((GameEventArgs)surgeAbilityEventArgs).NeedResponse);
}
    }
}
