// <copyright file="AbilityTest.GetAbility.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Descent.Model.Event
{
    public partial class AbilityTest
    {
[TestMethod]
[PexGeneratedBy(typeof(AbilityTest))]
public void GetAbility328()
{
    Ability ability;
    ability = this.GetAbility("  ");
    Assert.IsNotNull((object)ability);
    Assert.AreEqual<bool>(false, ability.Triggered);
}
[TestMethod]
[PexGeneratedBy(typeof(AbilityTest))]
public void GetAbility977()
{
    Ability ability;
    ability = this.GetAbility(" \0");
    Assert.IsNotNull((object)ability);
    Assert.AreEqual<bool>(false, ability.Triggered);
}
[TestMethod]
[PexGeneratedBy(typeof(AbilityTest))]
public void GetAbility256()
{
    Ability ability;
    ability = this.GetAbility("\0 ");
    Assert.IsNotNull((object)ability);
    Assert.AreEqual<bool>(false, ability.Triggered);
}
[TestMethod]
[PexGeneratedBy(typeof(AbilityTest))]
public void GetAbility811()
{
    Ability ability;
    ability = this.GetAbility("\u0a26\u6506");
    Assert.IsNotNull((object)ability);
    Assert.AreEqual<bool>(false, ability.Triggered);
}
[TestMethod]
[PexGeneratedBy(typeof(AbilityTest))]
public void GetAbility995()
{
    Ability ability;
    ability = this.GetAbility(" ");
    Assert.IsNotNull((object)ability);
    Assert.AreEqual<bool>(false, ability.Triggered);
}
[TestMethod]
[PexGeneratedBy(typeof(AbilityTest))]
public void GetAbility69()
{
    Ability ability;
    ability = this.GetAbility("\0");
    Assert.IsNotNull((object)ability);
    Assert.AreEqual<bool>(false, ability.Triggered);
}
[TestMethod]
[PexGeneratedBy(typeof(AbilityTest))]
public void GetAbility64()
{
    Ability ability;
    ability = this.GetAbility("");
    Assert.IsNotNull((object)ability);
    Assert.AreEqual<bool>(false, ability.Triggered);
}
[TestMethod]
[PexGeneratedBy(typeof(AbilityTest))]
public void GetAbility304()
{
    Ability ability;
    ability = this.GetAbility((string)null);
    Assert.IsNotNull((object)ability);
    Assert.AreEqual<bool>(false, ability.Triggered);
}
    }
}
