// <copyright file="AbilityTest.Apply.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Descent.Model.Player.Figure;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Descent.Model.Event
{
    public partial class AbilityTest
    {
[TestMethod]
[PexGeneratedBy(typeof(AbilityTest))]
public void Apply211()
{
    Ability ability;
    ability = new Ability();
    ability.Apply((global::Descent.Model.Player.Figure.Figure)null);
    this.Apply(ability, (global::Descent.Model.Player.Figure.Figure)null);
    Assert.IsNotNull((object)ability);
    Assert.AreEqual<bool>(false, ability.Triggered);
}
    }
}
