// <copyright file="BoardTest.HeroesInTownGet.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Descent.Model.Player.Figure;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Descent.Model.Board
{
    public partial class BoardTest
    {
[TestMethod]
[PexGeneratedBy(typeof(BoardTest))]
public void HeroesInTownGet564()
{
    global::Descent.Model.Board.Board board;
    Hero[] heros;
    board = new global::Descent.Model.Board.Board(2, 2, (Texture2D)null);
    heros = this.HeroesInTownGet(board);
    Assert.IsNotNull((object)heros);
    Assert.AreEqual<int>(0, heros.Length);
    Assert.IsNotNull((object)board);
    Assert.AreEqual<int>(2, board.Width);
    Assert.AreEqual<int>(2, board.Height);
    Assert.IsNotNull(board.FiguresOnBoard);
    Assert.IsNotNull(board.FiguresOnBoard.Comparer);
    Assert.AreEqual<int>(0, board.FiguresOnBoard.Count);
    Assert.IsNull(board.FloorTexture);
}
    }
}
