// <copyright file="BoardTest.SquareVisibleByPlayers.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Descent.Model.Board
{
    public partial class BoardTest
    {
[TestMethod]
[PexGeneratedBy(typeof(BoardTest))]
public void SquareVisibleByPlayers55()
{
    global::Descent.Model.Board.Board board;
    bool b;
    board = new global::Descent.Model.Board.Board(1022, 2, (Texture2D)null);
    b = this.SquareVisibleByPlayers(board, 1073742844, 0);
    Assert.AreEqual<bool>(false, b);
    Assert.IsNotNull((object)board);
    Assert.AreEqual<int>(1022, board.Width);
    Assert.AreEqual<int>(2, board.Height);
    Assert.IsNotNull(board.FiguresOnBoard);
    Assert.IsNotNull(board.FiguresOnBoard.Comparer);
    Assert.AreEqual<int>(0, board.FiguresOnBoard.Count);
    Assert.IsNull(board.FloorTexture);
}
[TestMethod]
[PexGeneratedBy(typeof(BoardTest))]
public void SquareVisibleByPlayers742()
{
    global::Descent.Model.Board.Board board;
    bool b;
    board = new global::Descent.Model.Board.Board(2, 2, (Texture2D)null);
    b = this.SquareVisibleByPlayers(board, int.MinValue, 0);
    Assert.AreEqual<bool>(false, b);
    Assert.IsNotNull((object)board);
    Assert.AreEqual<int>(2, board.Width);
    Assert.AreEqual<int>(2, board.Height);
    Assert.IsNotNull(board.FiguresOnBoard);
    Assert.IsNotNull(board.FiguresOnBoard.Comparer);
    Assert.AreEqual<int>(0, board.FiguresOnBoard.Count);
    Assert.IsNull(board.FloorTexture);
}
[TestMethod]
[PexGeneratedBy(typeof(BoardTest))]
public void SquareVisibleByPlayers607()
{
    global::Descent.Model.Board.Board board;
    bool b;
    board = new global::Descent.Model.Board.Board(2, 2, (Texture2D)null);
    b = this.SquareVisibleByPlayers(board, 0, int.MinValue);
    Assert.AreEqual<bool>(false, b);
    Assert.IsNotNull((object)board);
    Assert.AreEqual<int>(2, board.Width);
    Assert.AreEqual<int>(2, board.Height);
    Assert.IsNotNull(board.FiguresOnBoard);
    Assert.IsNotNull(board.FiguresOnBoard.Comparer);
    Assert.AreEqual<int>(0, board.FiguresOnBoard.Count);
    Assert.IsNull(board.FloorTexture);
}
[TestMethod]
[PexGeneratedBy(typeof(BoardTest))]
public void SquareVisibleByPlayers743()
{
    global::Descent.Model.Board.Board board;
    bool b;
    board = new global::Descent.Model.Board.Board(2, 2, (Texture2D)null);
    b = this.SquareVisibleByPlayers(board, 0, 0);
    Assert.AreEqual<bool>(false, b);
    Assert.IsNotNull((object)board);
    Assert.AreEqual<int>(2, board.Width);
    Assert.AreEqual<int>(2, board.Height);
    Assert.IsNotNull(board.FiguresOnBoard);
    Assert.IsNotNull(board.FiguresOnBoard.Comparer);
    Assert.AreEqual<int>(0, board.FiguresOnBoard.Count);
    Assert.IsNull(board.FloorTexture);
}
    }
}
