// <copyright file="DoorTest.IsAdjecentSquare.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Descent.Model.Board
{
    public partial class DoorTest
    {
[TestMethod]
[PexGeneratedBy(typeof(DoorTest))]
public void IsAdjecentSquare720()
{
    Door door;
    bool b;
    door = new Door
               (1, default(Point), default(Point), 0, default(Point), default(Point), 
                                                      Orientation.H, RuneKey.Red, (Texture2D)null);
    door.Opened = false;
    Point s0 = default(Point);
    s0.X = default(int);
    s0.Y = 1;
    b = this.IsAdjecentSquare(door, s0);
    Assert.AreEqual<bool>(false, b);
    Assert.IsNotNull((object)door);
    Assert.AreEqual<bool>(false, door.Opened);
    Assert.AreEqual<bool>(true, door.IsRuneDoor);
    Assert.AreEqual<RuneKey>(RuneKey.Red, door.KeyColor);
    Assert.AreEqual<Orientation>(Orientation.H, door.Orientation);
    Assert.IsNotNull(door.Areas);
    Assert.AreEqual<int>(2, door.Areas.Length);
    Assert.AreEqual<int>(0, door.Areas[0]);
    Assert.AreEqual<int>(0, door.Areas[1]);
    Assert.IsNull(door.Texture);
}
[TestMethod]
[PexGeneratedBy(typeof(DoorTest))]
public void IsAdjecentSquare991()
{
    Door door;
    bool b;
    door = new Door
               (1, default(Point), default(Point), 0, default(Point), default(Point), 
                                                      Orientation.H, RuneKey.Red, (Texture2D)null);
    door.Opened = false;
    Point s0 = default(Point);
    s0.X = 1;
    s0.Y = default(int);
    b = this.IsAdjecentSquare(door, s0);
    Assert.AreEqual<bool>(false, b);
    Assert.IsNotNull((object)door);
    Assert.AreEqual<bool>(false, door.Opened);
    Assert.AreEqual<bool>(true, door.IsRuneDoor);
    Assert.AreEqual<RuneKey>(RuneKey.Red, door.KeyColor);
    Assert.AreEqual<Orientation>(Orientation.H, door.Orientation);
    Assert.IsNotNull(door.Areas);
    Assert.AreEqual<int>(2, door.Areas.Length);
    Assert.AreEqual<int>(0, door.Areas[0]);
    Assert.AreEqual<int>(0, door.Areas[1]);
    Assert.IsNull(door.Texture);
}
[TestMethod]
[PexGeneratedBy(typeof(DoorTest))]
public void IsAdjecentSquare739()
{
    Door door;
    bool b;
    door = new Door
               (1, default(Point), default(Point), 0, default(Point), default(Point), 
                                                      Orientation.H, RuneKey.Red, (Texture2D)null);
    door.Opened = false;
    b = this.IsAdjecentSquare(door, default(Point));
    Assert.AreEqual<bool>(true, b);
    Assert.IsNotNull((object)door);
    Assert.AreEqual<bool>(false, door.Opened);
    Assert.AreEqual<bool>(true, door.IsRuneDoor);
    Assert.AreEqual<RuneKey>(RuneKey.Red, door.KeyColor);
    Assert.AreEqual<Orientation>(Orientation.H, door.Orientation);
    Assert.IsNotNull(door.Areas);
    Assert.AreEqual<int>(2, door.Areas.Length);
    Assert.AreEqual<int>(0, door.Areas[0]);
    Assert.AreEqual<int>(0, door.Areas[1]);
    Assert.IsNull(door.Texture);
}
    }
}
