// <copyright file="DoorTest.TopLeftCornerGet.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Descent.Model.Board
{
    public partial class DoorTest
    {
[TestMethod]
[PexGeneratedBy(typeof(DoorTest))]
public void TopLeftCornerGet332()
{
    Door door;
    Point point;
    Point s0 = default(Point);
    s0.X = -2147483520;
    s0.Y = 1;
    door = new Door(1, s0, default(Point), 256, default(Point), default(Point), 
                                                Orientation.H, RuneKey.Red, (Texture2D)null);
    door.Opened = false;
    point = this.TopLeftCornerGet(door);
    Assert.AreEqual<int>(-2147483520, point.X);
    Assert.AreEqual<int>(1, point.Y);
    Assert.IsNotNull((object)door);
    Assert.AreEqual<bool>(false, door.Opened);
    Assert.AreEqual<bool>(true, door.IsRuneDoor);
    Assert.AreEqual<RuneKey>(RuneKey.Red, door.KeyColor);
    Assert.AreEqual<Orientation>(Orientation.H, door.Orientation);
    Assert.IsNotNull(door.Areas);
    Assert.AreEqual<int>(2, door.Areas.Length);
    Assert.AreEqual<int>(1, door.Areas[0]);
    Assert.AreEqual<int>(256, door.Areas[1]);
    Assert.IsNull(door.Texture);
}
[TestMethod]
[PexGeneratedBy(typeof(DoorTest))]
public void TopLeftCornerGet54001()
{
    Door door;
    Point point;
    Point s0 = default(Point);
    s0.X = 256;
    s0.Y = default(int);
    Point s1 = default(Point);
    s1.X = default(int);
    s1.Y = 1;
    door = new Door(1, s0, s1, 0, default(Point), default(Point), 
                                  Orientation.H, RuneKey.Red, (Texture2D)null);
    door.Opened = false;
    point = this.TopLeftCornerGet(door);
    Assert.AreEqual<int>(0, point.X);
    Assert.AreEqual<int>(0, point.Y);
    Assert.IsNotNull((object)door);
    Assert.AreEqual<bool>(false, door.Opened);
    Assert.AreEqual<bool>(true, door.IsRuneDoor);
    Assert.AreEqual<RuneKey>(RuneKey.Red, door.KeyColor);
    Assert.AreEqual<Orientation>(Orientation.H, door.Orientation);
    Assert.IsNotNull(door.Areas);
    Assert.AreEqual<int>(2, door.Areas.Length);
    Assert.AreEqual<int>(0, door.Areas[0]);
    Assert.AreEqual<int>(0, door.Areas[1]);
    Assert.IsNull(door.Texture);
}
[TestMethod]
[PexGeneratedBy(typeof(DoorTest))]
public void TopLeftCornerGet540()
{
    Door door;
    Point point;
    door = new Door
               (1, default(Point), default(Point), 0, default(Point), default(Point), 
                                                      Orientation.H, RuneKey.Red, (Texture2D)null);
    door.Opened = false;
    point = this.TopLeftCornerGet(door);
    Assert.AreEqual<int>(0, point.X);
    Assert.AreEqual<int>(0, point.Y);
    Assert.IsNotNull((object)door);
    Assert.AreEqual<bool>(false, door.Opened);
    Assert.AreEqual<bool>(true, door.IsRuneDoor);
    Assert.AreEqual<RuneKey>(RuneKey.Red, door.KeyColor);
    Assert.AreEqual<Orientation>(Orientation.H, door.Orientation);
    Assert.IsNotNull(door.Areas);
    Assert.AreEqual<int>(2, door.Areas.Length);
    Assert.AreEqual<int>(0, door.Areas[0]);
    Assert.AreEqual<int>(0, door.Areas[1]);
    Assert.IsNull(door.Texture);
}
    }
}
