// <copyright file="SquareTest.AreaGet.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Descent.Model.Board.Marker;
using Descent.Model.Player.Figure;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Descent.Model.Board
{
    public partial class SquareTest
    {
[TestMethod]
[PexGeneratedBy(typeof(SquareTest))]
public void AreaGet298()
{
    int i;
    Square s0 = new Square(0);
    s0.Marker = (global::Descent.Model.Board.Marker.Marker)null;
    s0.Figure = (global::Descent.Model.Player.Figure.Figure)null;
    i = this.AreaGet(s0);
    Assert.AreEqual<int>(0, i);
    Assert.IsNotNull((object)s0);
    Assert.AreEqual<int>(0, s0.Area);
    Assert.IsNull(s0.Marker);
    Assert.IsNull(s0.Figure);
}
    }
}
