// <copyright file="ChestMarkerTest.Constructor.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Descent.Model.Player.Figure.HeroStuff;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;

namespace Descent.Model.Board.Marker
{
    public partial class ChestMarkerTest
    {
[TestMethod]
[PexGeneratedBy(typeof(ChestMarkerTest))]
public void Constructor932()
{
    ChestMarker chestMarker;
    chestMarker =
      this.Constructor(0, "\0", 0, EquipmentRarity.Common, (Texture2D)null);
    Assert.IsNotNull((object)chestMarker);
    Assert.AreEqual<int>
        (0, ((global::Descent.Model.Board.Marker.Marker)chestMarker).Id);
    Assert.AreEqual<string>
        ("\0", ((global::Descent.Model.Board.Marker.Marker)chestMarker).Name);
    Assert.IsNull(((global::Descent.Model.Board.Marker.Marker)chestMarker).Texture);
    Assert.AreEqual<int>
        (0, ((global::Descent.Model.Board.Marker.Marker)chestMarker).MovementPoints);
}
[TestMethod]
[PexGeneratedBy(typeof(ChestMarkerTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void ConstructorThrowsContractException209()
{
    try
    {
      ChestMarker chestMarker;
      chestMarker =
        this.Constructor(0, "", 0, EquipmentRarity.Common, (Texture2D)null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(ChestMarkerTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void ConstructorThrowsContractException751()
{
    try
    {
      ChestMarker chestMarker;
      chestMarker = this.Constructor
                        (0, (string)null, 0, EquipmentRarity.Common, (Texture2D)null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
    }
}
