// <copyright file="MoneyMarkerTest.Constructor.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;

namespace Descent.Model.Board.Marker
{
    public partial class MoneyMarkerTest
    {
[TestMethod]
[PexGeneratedBy(typeof(MoneyMarkerTest))]
public void Constructor85()
{
    MoneyMarker moneyMarker;
    moneyMarker = this.Constructor(0, "\0", (Texture2D)null, 0);
    Assert.IsNotNull((object)moneyMarker);
    Assert.AreEqual<int>
        (0, ((global::Descent.Model.Board.Marker.Marker)moneyMarker).Id);
    Assert.AreEqual<string>
        ("\0", ((global::Descent.Model.Board.Marker.Marker)moneyMarker).Name);
    Assert.IsNull(((global::Descent.Model.Board.Marker.Marker)moneyMarker).Texture);
    Assert.AreEqual<int>
        (0, ((global::Descent.Model.Board.Marker.Marker)moneyMarker).MovementPoints);
}
[TestMethod]
[PexGeneratedBy(typeof(MoneyMarkerTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void ConstructorThrowsContractException807()
{
    try
    {
      MoneyMarker moneyMarker;
      moneyMarker = this.Constructor(0, "", (Texture2D)null, 0);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(MoneyMarkerTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void ConstructorThrowsContractException938()
{
    try
    {
      MoneyMarker moneyMarker;
      moneyMarker = this.Constructor(0, (string)null, (Texture2D)null, 0);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
    }
}
