// <copyright file="ChatMessageEventArgsTest.ToString01.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Descent.Messaging.Events
{
    public partial class ChatMessageEventArgsTest
    {
[TestMethod]
[PexGeneratedBy(typeof(ChatMessageEventArgsTest))]
public void ToString01258()
{
    ChatMessageEventArgs chatMessageEventArgs;
    string s;
    chatMessageEventArgs = new ChatMessageEventArgs("\0");
    ((GameEventArgs)chatMessageEventArgs).SenderId = 0;
    ((GameEventArgs)chatMessageEventArgs).EventId = (string)null;
    ((GameEventArgs)chatMessageEventArgs).EventType = (EventType)0;
    ((GameEventArgs)chatMessageEventArgs).NeedResponse = false;
    s = this.ToString01(chatMessageEventArgs);
    Assert.AreEqual<string>("\0", s);
    Assert.IsNotNull((object)chatMessageEventArgs);
    Assert.AreEqual<string>("\0", chatMessageEventArgs.Message);
    Assert.AreEqual<int>(0, ((GameEventArgs)chatMessageEventArgs).SenderId);
    Assert.AreEqual<string>
        ((string)null, ((GameEventArgs)chatMessageEventArgs).EventId);
    Assert.AreEqual<EventType>
        ((EventType)0, ((GameEventArgs)chatMessageEventArgs).EventType);
    Assert.AreEqual<bool>(false, ((GameEventArgs)chatMessageEventArgs).NeedResponse);
}
    }
}
