// <copyright file="ChestEventArgsTest.Constructor01.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;

namespace Descent.Messaging.Events
{
    public partial class ChestEventArgsTest
    {
[TestMethod]
[PexGeneratedBy(typeof(ChestEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException626()
{
    try
    {
      ChestEventArgs chestEventArgs;
      string[] ss = new string[1];
      ss[0] = "-0";
      chestEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(ChestEventArgsTest))]
public void Constructor01353()
{
    ChestEventArgs chestEventArgs;
    string[] ss = new string[1];
    ss[0] = "1";
    chestEventArgs = this.Constructor01(ss);
    Assert.IsNotNull((object)chestEventArgs);
    Assert.AreEqual<int>(1, chestEventArgs.ChestId);
    Assert.AreEqual<int>(0, ((GameEventArgs)chestEventArgs).SenderId);
    Assert.AreEqual<string>((string)null, ((GameEventArgs)chestEventArgs).EventId);
    Assert.AreEqual<EventType>
        ((EventType)0, ((GameEventArgs)chestEventArgs).EventType);
    Assert.AreEqual<bool>(false, ((GameEventArgs)chestEventArgs).NeedResponse);
}
[TestMethod]
[PexGeneratedBy(typeof(ChestEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException754()
{
    try
    {
      ChestEventArgs chestEventArgs;
      string[] ss = new string[1];
      ss[0] = "-\0";
      chestEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(ChestEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException810()
{
    try
    {
      ChestEventArgs chestEventArgs;
      string[] ss = new string[1];
      ss[0] = "0\0";
      chestEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(ChestEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException166()
{
    try
    {
      ChestEventArgs chestEventArgs;
      string[] ss = new string[1];
      ss[0] = "-";
      chestEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(ChestEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException487()
{
    try
    {
      ChestEventArgs chestEventArgs;
      string[] ss = new string[1];
      ss[0] = ":";
      chestEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(ChestEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException744()
{
    try
    {
      ChestEventArgs chestEventArgs;
      string[] ss = new string[1];
      ss[0] = "0";
      chestEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(ChestEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException105()
{
    try
    {
      ChestEventArgs chestEventArgs;
      string[] ss = new string[1];
      ss[0] = "\u0001";
      chestEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(ChestEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException88()
{
    try
    {
      ChestEventArgs chestEventArgs;
      string[] ss = new string[1];
      ss[0] = "\0";
      chestEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(ChestEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException276()
{
    try
    {
      ChestEventArgs chestEventArgs;
      string[] ss = new string[1];
      ss[0] = "";
      chestEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(ChestEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException765()
{
    try
    {
      ChestEventArgs chestEventArgs;
      string[] ss = new string[1];
      chestEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(ChestEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException629()
{
    try
    {
      ChestEventArgs chestEventArgs;
      string[] ss = new string[0];
      chestEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(ChestEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException196()
{
    try
    {
      ChestEventArgs chestEventArgs;
      chestEventArgs = this.Constructor01((string[])null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(ChestEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void ConstructorThrowsContractException400()
{
    try
    {
      ChestEventArgs chestEventArgs;
      chestEventArgs = this.Constructor(int.MinValue);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(ChestEventArgsTest))]
public void Constructor553()
{
    ChestEventArgs chestEventArgs;
    chestEventArgs = this.Constructor(0);
    Assert.IsNotNull((object)chestEventArgs);
    Assert.AreEqual<int>(0, chestEventArgs.ChestId);
    Assert.AreEqual<int>(0, ((GameEventArgs)chestEventArgs).SenderId);
    Assert.AreEqual<string>((string)null, ((GameEventArgs)chestEventArgs).EventId);
    Assert.AreEqual<EventType>
        ((EventType)0, ((GameEventArgs)chestEventArgs).EventType);
    Assert.AreEqual<bool>(false, ((GameEventArgs)chestEventArgs).NeedResponse);
}
    }
}
