// <copyright file="EquipEventArgsTest.Constructor01.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;

namespace Descent.Messaging.Events
{
    public partial class EquipEventArgsTest
    {
[TestMethod]
[PexGeneratedBy(typeof(EquipEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException472()
{
    try
    {
      EquipEventArgs equipEventArgs;
      string[] ss = new string[2];
      ss[0] = "-0";
      ss[1] = "-";
      equipEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(EquipEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException577()
{
    try
    {
      EquipEventArgs equipEventArgs;
      string[] ss = new string[2];
      ss[0] = "-00\0";
      ss[1] = "\0";
      equipEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(EquipEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException468()
{
    try
    {
      EquipEventArgs equipEventArgs;
      string[] ss = new string[2];
      ss[0] = "-0\0";
      ss[1] = "\0";
      equipEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(EquipEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException554()
{
    try
    {
      EquipEventArgs equipEventArgs;
      string[] ss = new string[2];
      ss[0] = "-0\0";
      equipEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(EquipEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException511()
{
    try
    {
      EquipEventArgs equipEventArgs;
      string[] ss = new string[2];
      ss[0] = "-\0";
      ss[1] = "-\0";
      equipEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(EquipEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException65()
{
    try
    {
      EquipEventArgs equipEventArgs;
      string[] ss = new string[2];
      ss[0] = ":";
      ss[1] = ":";
      equipEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(EquipEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException516()
{
    try
    {
      EquipEventArgs equipEventArgs;
      string[] ss = new string[2];
      ss[0] = "-";
      ss[1] = "-";
      equipEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(EquipEventArgsTest))]
public void Constructor01212()
{
    EquipEventArgs equipEventArgs;
    string[] ss = new string[2];
    ss[0] = "0";
    ss[1] = "0";
    equipEventArgs = this.Constructor01(ss);
    Assert.IsNotNull((object)equipEventArgs);
    Assert.AreEqual<int>(0, equipEventArgs.EquipmentId);
    Assert.AreEqual<int>(0, equipEventArgs.InventoryField);
    Assert.AreEqual<int>(0, ((GameEventArgs)equipEventArgs).SenderId);
    Assert.AreEqual<string>((string)null, ((GameEventArgs)equipEventArgs).EventId);
    Assert.AreEqual<EventType>
        ((EventType)0, ((GameEventArgs)equipEventArgs).EventType);
    Assert.AreEqual<bool>(false, ((GameEventArgs)equipEventArgs).NeedResponse);
}
[TestMethod]
[PexGeneratedBy(typeof(EquipEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException940()
{
    try
    {
      EquipEventArgs equipEventArgs;
      string[] ss = new string[2];
      ss[0] = "\u0001";
      ss[1] = "\u0001";
      equipEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(EquipEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException297()
{
    try
    {
      EquipEventArgs equipEventArgs;
      string[] ss = new string[2];
      ss[0] = "\0\0";
      ss[1] = "\0\0";
      equipEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(EquipEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException40()
{
    try
    {
      EquipEventArgs equipEventArgs;
      string[] ss = new string[2];
      ss[0] = "";
      ss[1] = "";
      equipEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(EquipEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException339()
{
    try
    {
      EquipEventArgs equipEventArgs;
      string[] ss = new string[2];
      equipEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(EquipEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException245()
{
    try
    {
      EquipEventArgs equipEventArgs;
      string[] ss = new string[0];
      equipEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(EquipEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException698()
{
    try
    {
      EquipEventArgs equipEventArgs;
      equipEventArgs = this.Constructor01((string[])null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(EquipEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void ConstructorThrowsContractException423()
{
    try
    {
      EquipEventArgs equipEventArgs;
      equipEventArgs = this.Constructor(1, int.MinValue);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(EquipEventArgsTest))]
public void Constructor268()
{
    EquipEventArgs equipEventArgs;
    equipEventArgs = this.Constructor(1, 0);
    Assert.IsNotNull((object)equipEventArgs);
    Assert.AreEqual<int>(1, equipEventArgs.EquipmentId);
    Assert.AreEqual<int>(0, equipEventArgs.InventoryField);
    Assert.AreEqual<int>(0, ((GameEventArgs)equipEventArgs).SenderId);
    Assert.AreEqual<string>((string)null, ((GameEventArgs)equipEventArgs).EventId);
    Assert.AreEqual<EventType>
        ((EventType)0, ((GameEventArgs)equipEventArgs).EventType);
    Assert.AreEqual<bool>(false, ((GameEventArgs)equipEventArgs).NeedResponse);
}
[TestMethod]
[PexGeneratedBy(typeof(EquipEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void ConstructorThrowsContractException483()
{
    try
    {
      EquipEventArgs equipEventArgs;
      equipEventArgs = this.Constructor(0, 0);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
    }
}
