// <copyright file="GiveEquipmentEventArgsTest.PopulateWithArgs.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;

namespace Descent.Messaging.Events
{
    public partial class GiveEquipmentEventArgsTest
    {
[TestMethod]
[PexGeneratedBy(typeof(GiveEquipmentEventArgsTest))]
public void PopulateWithArgs660()
{
    GiveEquipmentEventArgs giveEquipmentEventArgs;
    giveEquipmentEventArgs = new GiveEquipmentEventArgs(1, 1, false);
    ((GameEventArgs)giveEquipmentEventArgs).SenderId = 0;
    ((GameEventArgs)giveEquipmentEventArgs).EventId = (string)null;
    ((GameEventArgs)giveEquipmentEventArgs).EventType = (EventType)0;
    ((GameEventArgs)giveEquipmentEventArgs).NeedResponse = false;
    string[] ss = new string[3];
    ss[0] = "1";
    ss[1] = "1";
    ss[2] = "0";
    this.PopulateWithArgs(giveEquipmentEventArgs, ss);
    Assert.IsNotNull((object)giveEquipmentEventArgs);
    Assert.AreEqual<int>(1, giveEquipmentEventArgs.PlayerId);
    Assert.AreEqual<int>(1, giveEquipmentEventArgs.EquipmentId);
    Assert.AreEqual<bool>(false, giveEquipmentEventArgs.Free);
    Assert.AreEqual<int>(0, ((GameEventArgs)giveEquipmentEventArgs).SenderId);
    Assert.AreEqual<string>
        ((string)null, ((GameEventArgs)giveEquipmentEventArgs).EventId);
    Assert.AreEqual<EventType>
        ((EventType)0, ((GameEventArgs)giveEquipmentEventArgs).EventType);
    Assert.AreEqual<bool>
        (false, ((GameEventArgs)giveEquipmentEventArgs).NeedResponse);
}
[TestMethod]
[PexGeneratedBy(typeof(GiveEquipmentEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException931()
{
    try
    {
      GiveEquipmentEventArgs giveEquipmentEventArgs;
      giveEquipmentEventArgs = new GiveEquipmentEventArgs(1, 1, false);
      ((GameEventArgs)giveEquipmentEventArgs).SenderId = 0;
      ((GameEventArgs)giveEquipmentEventArgs).EventId = (string)null;
      ((GameEventArgs)giveEquipmentEventArgs).EventType = (EventType)0;
      ((GameEventArgs)giveEquipmentEventArgs).NeedResponse = false;
      string[] ss = new string[3];
      ss[0] = "1";
      ss[1] = "0";
      ss[2] = "0";
      this.PopulateWithArgs(giveEquipmentEventArgs, ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(GiveEquipmentEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException165()
{
    try
    {
      GiveEquipmentEventArgs giveEquipmentEventArgs;
      giveEquipmentEventArgs = new GiveEquipmentEventArgs(1, 1, false);
      ((GameEventArgs)giveEquipmentEventArgs).SenderId = 0;
      ((GameEventArgs)giveEquipmentEventArgs).EventId = (string)null;
      ((GameEventArgs)giveEquipmentEventArgs).EventType = (EventType)0;
      ((GameEventArgs)giveEquipmentEventArgs).NeedResponse = false;
      string[] ss = new string[3];
      ss[0] = "-0";
      ss[1] = "-0";
      ss[2] = "-0";
      this.PopulateWithArgs(giveEquipmentEventArgs, ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(GiveEquipmentEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException663()
{
    try
    {
      GiveEquipmentEventArgs giveEquipmentEventArgs;
      giveEquipmentEventArgs = new GiveEquipmentEventArgs(1, 1, false);
      ((GameEventArgs)giveEquipmentEventArgs).SenderId = 0;
      ((GameEventArgs)giveEquipmentEventArgs).EventId = (string)null;
      ((GameEventArgs)giveEquipmentEventArgs).EventType = (EventType)0;
      ((GameEventArgs)giveEquipmentEventArgs).NeedResponse = false;
      string[] ss = new string[3];
      ss[0] = "-\0";
      ss[1] = "-\0";
      ss[2] = "-\0";
      this.PopulateWithArgs(giveEquipmentEventArgs, ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(GiveEquipmentEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException614()
{
    try
    {
      GiveEquipmentEventArgs giveEquipmentEventArgs;
      giveEquipmentEventArgs = new GiveEquipmentEventArgs(1, 1, false);
      ((GameEventArgs)giveEquipmentEventArgs).SenderId = 0;
      ((GameEventArgs)giveEquipmentEventArgs).EventId = (string)null;
      ((GameEventArgs)giveEquipmentEventArgs).EventType = (EventType)0;
      ((GameEventArgs)giveEquipmentEventArgs).NeedResponse = false;
      string[] ss = new string[3];
      ss[0] = "0\0";
      ss[1] = "0\0";
      ss[2] = "0\0";
      this.PopulateWithArgs(giveEquipmentEventArgs, ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(GiveEquipmentEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException302()
{
    try
    {
      GiveEquipmentEventArgs giveEquipmentEventArgs;
      giveEquipmentEventArgs = new GiveEquipmentEventArgs(1, 1, false);
      ((GameEventArgs)giveEquipmentEventArgs).SenderId = 0;
      ((GameEventArgs)giveEquipmentEventArgs).EventId = (string)null;
      ((GameEventArgs)giveEquipmentEventArgs).EventType = (EventType)0;
      ((GameEventArgs)giveEquipmentEventArgs).NeedResponse = false;
      string[] ss = new string[3];
      ss[0] = ":";
      ss[1] = ":";
      ss[2] = ":";
      this.PopulateWithArgs(giveEquipmentEventArgs, ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(GiveEquipmentEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException575()
{
    try
    {
      GiveEquipmentEventArgs giveEquipmentEventArgs;
      giveEquipmentEventArgs = new GiveEquipmentEventArgs(1, 1, false);
      ((GameEventArgs)giveEquipmentEventArgs).SenderId = 0;
      ((GameEventArgs)giveEquipmentEventArgs).EventId = (string)null;
      ((GameEventArgs)giveEquipmentEventArgs).EventType = (EventType)0;
      ((GameEventArgs)giveEquipmentEventArgs).NeedResponse = false;
      string[] ss = new string[3];
      ss[0] = "0";
      ss[1] = "0";
      ss[2] = "0";
      this.PopulateWithArgs(giveEquipmentEventArgs, ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(GiveEquipmentEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException320()
{
    try
    {
      GiveEquipmentEventArgs giveEquipmentEventArgs;
      giveEquipmentEventArgs = new GiveEquipmentEventArgs(1, 1, false);
      ((GameEventArgs)giveEquipmentEventArgs).SenderId = 0;
      ((GameEventArgs)giveEquipmentEventArgs).EventId = (string)null;
      ((GameEventArgs)giveEquipmentEventArgs).EventType = (EventType)0;
      ((GameEventArgs)giveEquipmentEventArgs).NeedResponse = false;
      string[] ss = new string[3];
      ss[0] = "-";
      ss[1] = "-";
      ss[2] = "-";
      this.PopulateWithArgs(giveEquipmentEventArgs, ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(GiveEquipmentEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException254()
{
    try
    {
      GiveEquipmentEventArgs giveEquipmentEventArgs;
      giveEquipmentEventArgs = new GiveEquipmentEventArgs(1, 1, false);
      ((GameEventArgs)giveEquipmentEventArgs).SenderId = 0;
      ((GameEventArgs)giveEquipmentEventArgs).EventId = (string)null;
      ((GameEventArgs)giveEquipmentEventArgs).EventType = (EventType)0;
      ((GameEventArgs)giveEquipmentEventArgs).NeedResponse = false;
      string[] ss = new string[3];
      ss[0] = "\u0001";
      ss[1] = "\u0001";
      ss[2] = "\u0001";
      this.PopulateWithArgs(giveEquipmentEventArgs, ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(GiveEquipmentEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException756()
{
    try
    {
      GiveEquipmentEventArgs giveEquipmentEventArgs;
      giveEquipmentEventArgs = new GiveEquipmentEventArgs(1, 1, false);
      ((GameEventArgs)giveEquipmentEventArgs).SenderId = 0;
      ((GameEventArgs)giveEquipmentEventArgs).EventId = (string)null;
      ((GameEventArgs)giveEquipmentEventArgs).EventType = (EventType)0;
      ((GameEventArgs)giveEquipmentEventArgs).NeedResponse = false;
      string[] ss = new string[3];
      ss[0] = "\0";
      ss[1] = "\0";
      ss[2] = "\0";
      this.PopulateWithArgs(giveEquipmentEventArgs, ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(GiveEquipmentEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException340()
{
    try
    {
      GiveEquipmentEventArgs giveEquipmentEventArgs;
      giveEquipmentEventArgs = new GiveEquipmentEventArgs(1, 1, false);
      ((GameEventArgs)giveEquipmentEventArgs).SenderId = 0;
      ((GameEventArgs)giveEquipmentEventArgs).EventId = (string)null;
      ((GameEventArgs)giveEquipmentEventArgs).EventType = (EventType)0;
      ((GameEventArgs)giveEquipmentEventArgs).NeedResponse = false;
      string[] ss = new string[3];
      ss[0] = "";
      ss[1] = "";
      ss[2] = "";
      this.PopulateWithArgs(giveEquipmentEventArgs, ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(GiveEquipmentEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException709()
{
    try
    {
      GiveEquipmentEventArgs giveEquipmentEventArgs;
      giveEquipmentEventArgs = new GiveEquipmentEventArgs(1, 1, false);
      ((GameEventArgs)giveEquipmentEventArgs).SenderId = 0;
      ((GameEventArgs)giveEquipmentEventArgs).EventId = (string)null;
      ((GameEventArgs)giveEquipmentEventArgs).EventType = (EventType)0;
      ((GameEventArgs)giveEquipmentEventArgs).NeedResponse = false;
      string[] ss = new string[3];
      this.PopulateWithArgs(giveEquipmentEventArgs, ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(GiveEquipmentEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException393()
{
    try
    {
      GiveEquipmentEventArgs giveEquipmentEventArgs;
      giveEquipmentEventArgs = new GiveEquipmentEventArgs(1, 1, false);
      ((GameEventArgs)giveEquipmentEventArgs).SenderId = 0;
      ((GameEventArgs)giveEquipmentEventArgs).EventId = (string)null;
      ((GameEventArgs)giveEquipmentEventArgs).EventType = (EventType)0;
      ((GameEventArgs)giveEquipmentEventArgs).NeedResponse = false;
      string[] ss = new string[0];
      this.PopulateWithArgs(giveEquipmentEventArgs, ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(GiveEquipmentEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException878()
{
    try
    {
      GiveEquipmentEventArgs giveEquipmentEventArgs;
      giveEquipmentEventArgs = new GiveEquipmentEventArgs(1, 1, false);
      ((GameEventArgs)giveEquipmentEventArgs).SenderId = 0;
      ((GameEventArgs)giveEquipmentEventArgs).EventId = (string)null;
      ((GameEventArgs)giveEquipmentEventArgs).EventType = (EventType)0;
      ((GameEventArgs)giveEquipmentEventArgs).NeedResponse = false;
      this.PopulateWithArgs(giveEquipmentEventArgs, (string[])null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
    }
}
