// <copyright file="RerollDicesEventArgsTest.ToString01.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Descent.Messaging.Events
{
    public partial class RerollDicesEventArgsTest
    {
[TestMethod]
[PexGeneratedBy(typeof(RerollDicesEventArgsTest))]
public void ToString01844()
{
    RerollDicesEventArgs rerollDicesEventArgs;
    string s;
    int[] ints = new int[3];
    ints[0] = int.MaxValue;
    ints[1] = int.MaxValue;
    rerollDicesEventArgs = new RerollDicesEventArgs(ints);
    ((GameEventArgs)rerollDicesEventArgs).SenderId = 0;
    ((GameEventArgs)rerollDicesEventArgs).EventId = (string)null;
    ((GameEventArgs)rerollDicesEventArgs).EventType = (EventType)0;
    ((GameEventArgs)rerollDicesEventArgs).NeedResponse = false;
    s = this.ToString01(rerollDicesEventArgs);
    Assert.AreEqual<string>("2147483647,2147483647,0", s);
    Assert.IsNotNull((object)rerollDicesEventArgs);
    Assert.IsNotNull(rerollDicesEventArgs.DiceIds);
    Assert.AreEqual<int>(3, rerollDicesEventArgs.DiceIds.Length);
    Assert.AreEqual<int>(int.MaxValue, rerollDicesEventArgs.DiceIds[0]);
    Assert.AreEqual<int>(int.MaxValue, rerollDicesEventArgs.DiceIds[1]);
    Assert.AreEqual<int>(0, rerollDicesEventArgs.DiceIds[2]);
    Assert.AreEqual<int>(0, ((GameEventArgs)rerollDicesEventArgs).SenderId);
    Assert.AreEqual<string>
        ((string)null, ((GameEventArgs)rerollDicesEventArgs).EventId);
    Assert.AreEqual<EventType>
        ((EventType)0, ((GameEventArgs)rerollDicesEventArgs).EventType);
    Assert.AreEqual<bool>(false, ((GameEventArgs)rerollDicesEventArgs).NeedResponse);
}
[TestMethod]
[PexGeneratedBy(typeof(RerollDicesEventArgsTest))]
public void ToString01839()
{
    RerollDicesEventArgs rerollDicesEventArgs;
    string s;
    int[] ints = new int[2];
    ints[0] = 113;
    rerollDicesEventArgs = new RerollDicesEventArgs(ints);
    ((GameEventArgs)rerollDicesEventArgs).SenderId = 0;
    ((GameEventArgs)rerollDicesEventArgs).EventId = (string)null;
    ((GameEventArgs)rerollDicesEventArgs).EventType = (EventType)0;
    ((GameEventArgs)rerollDicesEventArgs).NeedResponse = false;
    s = this.ToString01(rerollDicesEventArgs);
    Assert.AreEqual<string>("113,0", s);
    Assert.IsNotNull((object)rerollDicesEventArgs);
    Assert.IsNotNull(rerollDicesEventArgs.DiceIds);
    Assert.AreEqual<int>(2, rerollDicesEventArgs.DiceIds.Length);
    Assert.AreEqual<int>(113, rerollDicesEventArgs.DiceIds[0]);
    Assert.AreEqual<int>(0, rerollDicesEventArgs.DiceIds[1]);
    Assert.AreEqual<int>(0, ((GameEventArgs)rerollDicesEventArgs).SenderId);
    Assert.AreEqual<string>
        ((string)null, ((GameEventArgs)rerollDicesEventArgs).EventId);
    Assert.AreEqual<EventType>
        ((EventType)0, ((GameEventArgs)rerollDicesEventArgs).EventType);
    Assert.AreEqual<bool>(false, ((GameEventArgs)rerollDicesEventArgs).NeedResponse);
}
[TestMethod]
[PexGeneratedBy(typeof(RerollDicesEventArgsTest))]
public void ToString01191()
{
    RerollDicesEventArgs rerollDicesEventArgs;
    string s;
    int[] ints = new int[1];
    ints[0] = 1;
    rerollDicesEventArgs = new RerollDicesEventArgs(ints);
    ((GameEventArgs)rerollDicesEventArgs).SenderId = 0;
    ((GameEventArgs)rerollDicesEventArgs).EventId = (string)null;
    ((GameEventArgs)rerollDicesEventArgs).EventType = (EventType)0;
    ((GameEventArgs)rerollDicesEventArgs).NeedResponse = false;
    s = this.ToString01(rerollDicesEventArgs);
    Assert.AreEqual<string>("1", s);
    Assert.IsNotNull((object)rerollDicesEventArgs);
    Assert.IsNotNull(rerollDicesEventArgs.DiceIds);
    Assert.AreEqual<int>(1, rerollDicesEventArgs.DiceIds.Length);
    Assert.AreEqual<int>(1, rerollDicesEventArgs.DiceIds[0]);
    Assert.AreEqual<int>(0, ((GameEventArgs)rerollDicesEventArgs).SenderId);
    Assert.AreEqual<string>
        ((string)null, ((GameEventArgs)rerollDicesEventArgs).EventId);
    Assert.AreEqual<EventType>
        ((EventType)0, ((GameEventArgs)rerollDicesEventArgs).EventType);
    Assert.AreEqual<bool>(false, ((GameEventArgs)rerollDicesEventArgs).NeedResponse);
}
[TestMethod]
[PexGeneratedBy(typeof(RerollDicesEventArgsTest))]
public void ToString01640()
{
    RerollDicesEventArgs rerollDicesEventArgs;
    string s;
    int[] ints = new int[1];
    rerollDicesEventArgs = new RerollDicesEventArgs(ints);
    ((GameEventArgs)rerollDicesEventArgs).SenderId = 0;
    ((GameEventArgs)rerollDicesEventArgs).EventId = (string)null;
    ((GameEventArgs)rerollDicesEventArgs).EventType = (EventType)0;
    ((GameEventArgs)rerollDicesEventArgs).NeedResponse = false;
    s = this.ToString01(rerollDicesEventArgs);
    Assert.AreEqual<string>("0", s);
    Assert.IsNotNull((object)rerollDicesEventArgs);
    Assert.IsNotNull(rerollDicesEventArgs.DiceIds);
    Assert.AreEqual<int>(1, rerollDicesEventArgs.DiceIds.Length);
    Assert.AreEqual<int>(0, rerollDicesEventArgs.DiceIds[0]);
    Assert.AreEqual<int>(0, ((GameEventArgs)rerollDicesEventArgs).SenderId);
    Assert.AreEqual<string>
        ((string)null, ((GameEventArgs)rerollDicesEventArgs).EventId);
    Assert.AreEqual<EventType>
        ((EventType)0, ((GameEventArgs)rerollDicesEventArgs).EventType);
    Assert.AreEqual<bool>(false, ((GameEventArgs)rerollDicesEventArgs).NeedResponse);
}
    }
}
