// <copyright file="InflictWoundsEventArgsTest.Constructor01.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;

namespace Descent.Messaging.Events
{
    public partial class InflictWoundsEventArgsTest
    {
[TestMethod]
[PexGeneratedBy(typeof(InflictWoundsEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException613()
{
    try
    {
      InflictWoundsEventArgs inflictWoundsEventArgs;
      string[] ss = new string[4];
      ss[0] = "-0\0";
      ss[1] = "-0\0";
      ss[2] = "-0\0";
      ss[3] = "\0";
      inflictWoundsEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(InflictWoundsEventArgsTest))]
public void Constructor01873()
{
    InflictWoundsEventArgs inflictWoundsEventArgs;
    string[] ss = new string[4];
    ss[0] = "0";
    ss[1] = "0";
    ss[2] = "0";
    ss[3] = "0";
    inflictWoundsEventArgs = this.Constructor01(ss);
    Assert.IsNotNull((object)inflictWoundsEventArgs);
    Assert.AreEqual<int>(0, inflictWoundsEventArgs.X);
    Assert.AreEqual<int>(0, inflictWoundsEventArgs.Y);
    Assert.AreEqual<int>(0, inflictWoundsEventArgs.Damage);
    Assert.AreEqual<int>(0, inflictWoundsEventArgs.Pierce);
    Assert.AreEqual<int>(0, ((GameEventArgs)inflictWoundsEventArgs).SenderId);
    Assert.AreEqual<string>
        ((string)null, ((GameEventArgs)inflictWoundsEventArgs).EventId);
    Assert.AreEqual<EventType>
        ((EventType)0, ((GameEventArgs)inflictWoundsEventArgs).EventType);
    Assert.AreEqual<bool>
        (false, ((GameEventArgs)inflictWoundsEventArgs).NeedResponse);
}
[TestMethod]
[PexGeneratedBy(typeof(InflictWoundsEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException546()
{
    try
    {
      InflictWoundsEventArgs inflictWoundsEventArgs;
      string[] ss = new string[4];
      ss[0] = "-9";
      ss[1] = "-9";
      ss[2] = "-9";
      ss[3] = "-9";
      inflictWoundsEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(InflictWoundsEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException837()
{
    try
    {
      InflictWoundsEventArgs inflictWoundsEventArgs;
      string[] ss = new string[4];
      ss[0] = "-\0";
      ss[1] = "-\0";
      ss[2] = "-\0";
      ss[3] = "-\0";
      inflictWoundsEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(InflictWoundsEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException364()
{
    try
    {
      InflictWoundsEventArgs inflictWoundsEventArgs;
      string[] ss = new string[4];
      ss[0] = ":";
      ss[1] = ":";
      ss[2] = ":";
      ss[3] = ":";
      inflictWoundsEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(InflictWoundsEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException244()
{
    try
    {
      InflictWoundsEventArgs inflictWoundsEventArgs;
      string[] ss = new string[4];
      ss[0] = "-";
      ss[1] = "-";
      ss[2] = "-";
      ss[3] = "-";
      inflictWoundsEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(InflictWoundsEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException276()
{
    try
    {
      InflictWoundsEventArgs inflictWoundsEventArgs;
      string[] ss = new string[4];
      ss[0] = "\u0001";
      ss[1] = "\u0001";
      ss[2] = "\u0001";
      ss[3] = "\u0001";
      inflictWoundsEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(InflictWoundsEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException207()
{
    try
    {
      InflictWoundsEventArgs inflictWoundsEventArgs;
      string[] ss = new string[4];
      ss[0] = "\0\0\0\0";
      ss[1] = "\0\0\0\0";
      ss[2] = "\0\0\0\0";
      ss[3] = "\0\0\0\0";
      inflictWoundsEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(InflictWoundsEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException35()
{
    try
    {
      InflictWoundsEventArgs inflictWoundsEventArgs;
      string[] ss = new string[4];
      ss[0] = "";
      ss[1] = "";
      ss[2] = "";
      ss[3] = "";
      inflictWoundsEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(InflictWoundsEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException117()
{
    try
    {
      InflictWoundsEventArgs inflictWoundsEventArgs;
      string[] ss = new string[4];
      inflictWoundsEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(InflictWoundsEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException645()
{
    try
    {
      InflictWoundsEventArgs inflictWoundsEventArgs;
      string[] ss = new string[0];
      inflictWoundsEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(InflictWoundsEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException596()
{
    try
    {
      InflictWoundsEventArgs inflictWoundsEventArgs;
      inflictWoundsEventArgs = this.Constructor01((string[])null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(InflictWoundsEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void ConstructorThrowsContractException26()
{
    try
    {
      InflictWoundsEventArgs inflictWoundsEventArgs;
      inflictWoundsEventArgs = this.Constructor(int.MinValue, 0, 0, 0);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(InflictWoundsEventArgsTest))]
public void Constructor578()
{
    InflictWoundsEventArgs inflictWoundsEventArgs;
    inflictWoundsEventArgs = this.Constructor(0, 0, 0, 0);
    Assert.IsNotNull((object)inflictWoundsEventArgs);
    Assert.AreEqual<int>(0, inflictWoundsEventArgs.X);
    Assert.AreEqual<int>(0, inflictWoundsEventArgs.Y);
    Assert.AreEqual<int>(0, inflictWoundsEventArgs.Damage);
    Assert.AreEqual<int>(0, inflictWoundsEventArgs.Pierce);
    Assert.AreEqual<int>(0, ((GameEventArgs)inflictWoundsEventArgs).SenderId);
    Assert.AreEqual<string>
        ((string)null, ((GameEventArgs)inflictWoundsEventArgs).EventId);
    Assert.AreEqual<EventType>
        ((EventType)0, ((GameEventArgs)inflictWoundsEventArgs).EventType);
    Assert.AreEqual<bool>
        (false, ((GameEventArgs)inflictWoundsEventArgs).NeedResponse);
}
    }
}
