// <copyright file="InflictWoundsEventArgsTest.PopulateWithArgs.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;

namespace Descent.Messaging.Events
{
    public partial class InflictWoundsEventArgsTest
    {
[TestMethod]
[PexGeneratedBy(typeof(InflictWoundsEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException303()
{
    try
    {
      InflictWoundsEventArgs inflictWoundsEventArgs;
      inflictWoundsEventArgs = new InflictWoundsEventArgs(0, 0, 0, 0);
      ((GameEventArgs)inflictWoundsEventArgs).SenderId = 0;
      ((GameEventArgs)inflictWoundsEventArgs).EventId = (string)null;
      ((GameEventArgs)inflictWoundsEventArgs).EventType = (EventType)0;
      ((GameEventArgs)inflictWoundsEventArgs).NeedResponse = false;
      string[] ss = new string[4];
      ss[0] = "-0\0";
      ss[1] = "-0\0";
      ss[3] = "-0\0";
      this.PopulateWithArgs(inflictWoundsEventArgs, ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(InflictWoundsEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException196()
{
    try
    {
      InflictWoundsEventArgs inflictWoundsEventArgs;
      inflictWoundsEventArgs = new InflictWoundsEventArgs(0, 0, 0, 0);
      ((GameEventArgs)inflictWoundsEventArgs).SenderId = 0;
      ((GameEventArgs)inflictWoundsEventArgs).EventId = (string)null;
      ((GameEventArgs)inflictWoundsEventArgs).EventType = (EventType)0;
      ((GameEventArgs)inflictWoundsEventArgs).NeedResponse = false;
      string[] ss = new string[4];
      ss[0] = "-9";
      ss[1] = "-9";
      ss[2] = "-9";
      ss[3] = "-9";
      this.PopulateWithArgs(inflictWoundsEventArgs, ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(InflictWoundsEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException566()
{
    try
    {
      InflictWoundsEventArgs inflictWoundsEventArgs;
      inflictWoundsEventArgs = new InflictWoundsEventArgs(0, 0, 0, 0);
      ((GameEventArgs)inflictWoundsEventArgs).SenderId = 0;
      ((GameEventArgs)inflictWoundsEventArgs).EventId = (string)null;
      ((GameEventArgs)inflictWoundsEventArgs).EventType = (EventType)0;
      ((GameEventArgs)inflictWoundsEventArgs).NeedResponse = false;
      string[] ss = new string[4];
      ss[0] = "-\0";
      ss[1] = "-\0";
      ss[2] = "-\0";
      ss[3] = "-\0";
      this.PopulateWithArgs(inflictWoundsEventArgs, ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(InflictWoundsEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException243()
{
    try
    {
      InflictWoundsEventArgs inflictWoundsEventArgs;
      inflictWoundsEventArgs = new InflictWoundsEventArgs(0, 0, 0, 0);
      ((GameEventArgs)inflictWoundsEventArgs).SenderId = 0;
      ((GameEventArgs)inflictWoundsEventArgs).EventId = (string)null;
      ((GameEventArgs)inflictWoundsEventArgs).EventType = (EventType)0;
      ((GameEventArgs)inflictWoundsEventArgs).NeedResponse = false;
      string[] ss = new string[4];
      ss[0] = ":";
      ss[1] = ":";
      ss[2] = ":";
      ss[3] = ":";
      this.PopulateWithArgs(inflictWoundsEventArgs, ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(InflictWoundsEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException565()
{
    try
    {
      InflictWoundsEventArgs inflictWoundsEventArgs;
      inflictWoundsEventArgs = new InflictWoundsEventArgs(0, 0, 0, 0);
      ((GameEventArgs)inflictWoundsEventArgs).SenderId = 0;
      ((GameEventArgs)inflictWoundsEventArgs).EventId = (string)null;
      ((GameEventArgs)inflictWoundsEventArgs).EventType = (EventType)0;
      ((GameEventArgs)inflictWoundsEventArgs).NeedResponse = false;
      string[] ss = new string[4];
      ss[0] = "-";
      ss[1] = "-";
      ss[2] = "-";
      ss[3] = "-";
      this.PopulateWithArgs(inflictWoundsEventArgs, ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(InflictWoundsEventArgsTest))]
public void PopulateWithArgs898()
{
    InflictWoundsEventArgs inflictWoundsEventArgs;
    inflictWoundsEventArgs = new InflictWoundsEventArgs(0, 0, 0, 0);
    ((GameEventArgs)inflictWoundsEventArgs).SenderId = 0;
    ((GameEventArgs)inflictWoundsEventArgs).EventId = (string)null;
    ((GameEventArgs)inflictWoundsEventArgs).EventType = (EventType)0;
    ((GameEventArgs)inflictWoundsEventArgs).NeedResponse = false;
    string[] ss = new string[4];
    ss[0] = "0";
    ss[1] = "0";
    ss[2] = "0";
    ss[3] = "0";
    this.PopulateWithArgs(inflictWoundsEventArgs, ss);
    Assert.IsNotNull((object)inflictWoundsEventArgs);
    Assert.AreEqual<int>(0, inflictWoundsEventArgs.X);
    Assert.AreEqual<int>(0, inflictWoundsEventArgs.Y);
    Assert.AreEqual<int>(0, inflictWoundsEventArgs.Damage);
    Assert.AreEqual<int>(0, inflictWoundsEventArgs.Pierce);
    Assert.AreEqual<int>(0, ((GameEventArgs)inflictWoundsEventArgs).SenderId);
    Assert.AreEqual<string>
        ((string)null, ((GameEventArgs)inflictWoundsEventArgs).EventId);
    Assert.AreEqual<EventType>
        ((EventType)0, ((GameEventArgs)inflictWoundsEventArgs).EventType);
    Assert.AreEqual<bool>
        (false, ((GameEventArgs)inflictWoundsEventArgs).NeedResponse);
}
[TestMethod]
[PexGeneratedBy(typeof(InflictWoundsEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException541()
{
    try
    {
      InflictWoundsEventArgs inflictWoundsEventArgs;
      inflictWoundsEventArgs = new InflictWoundsEventArgs(0, 0, 0, 0);
      ((GameEventArgs)inflictWoundsEventArgs).SenderId = 0;
      ((GameEventArgs)inflictWoundsEventArgs).EventId = (string)null;
      ((GameEventArgs)inflictWoundsEventArgs).EventType = (EventType)0;
      ((GameEventArgs)inflictWoundsEventArgs).NeedResponse = false;
      string[] ss = new string[4];
      ss[0] = "\u0001";
      ss[1] = "\u0001";
      ss[2] = "\u0001";
      ss[3] = "\u0001";
      this.PopulateWithArgs(inflictWoundsEventArgs, ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(InflictWoundsEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException928()
{
    try
    {
      InflictWoundsEventArgs inflictWoundsEventArgs;
      inflictWoundsEventArgs = new InflictWoundsEventArgs(0, 0, 0, 0);
      ((GameEventArgs)inflictWoundsEventArgs).SenderId = 0;
      ((GameEventArgs)inflictWoundsEventArgs).EventId = (string)null;
      ((GameEventArgs)inflictWoundsEventArgs).EventType = (EventType)0;
      ((GameEventArgs)inflictWoundsEventArgs).NeedResponse = false;
      string[] ss = new string[4];
      ss[0] = "\0\0";
      ss[1] = "\0\0";
      ss[2] = "\0\0";
      ss[3] = "\0\0";
      this.PopulateWithArgs(inflictWoundsEventArgs, ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(InflictWoundsEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException875()
{
    try
    {
      InflictWoundsEventArgs inflictWoundsEventArgs;
      inflictWoundsEventArgs = new InflictWoundsEventArgs(0, 0, 0, 0);
      ((GameEventArgs)inflictWoundsEventArgs).SenderId = 0;
      ((GameEventArgs)inflictWoundsEventArgs).EventId = (string)null;
      ((GameEventArgs)inflictWoundsEventArgs).EventType = (EventType)0;
      ((GameEventArgs)inflictWoundsEventArgs).NeedResponse = false;
      string[] ss = new string[4];
      ss[0] = "";
      ss[1] = "";
      ss[2] = "";
      ss[3] = "";
      this.PopulateWithArgs(inflictWoundsEventArgs, ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(InflictWoundsEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException260()
{
    try
    {
      InflictWoundsEventArgs inflictWoundsEventArgs;
      inflictWoundsEventArgs = new InflictWoundsEventArgs(0, 0, 0, 0);
      ((GameEventArgs)inflictWoundsEventArgs).SenderId = 0;
      ((GameEventArgs)inflictWoundsEventArgs).EventId = (string)null;
      ((GameEventArgs)inflictWoundsEventArgs).EventType = (EventType)0;
      ((GameEventArgs)inflictWoundsEventArgs).NeedResponse = false;
      string[] ss = new string[4];
      this.PopulateWithArgs(inflictWoundsEventArgs, ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(InflictWoundsEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException403()
{
    try
    {
      InflictWoundsEventArgs inflictWoundsEventArgs;
      inflictWoundsEventArgs = new InflictWoundsEventArgs(0, 0, 0, 0);
      ((GameEventArgs)inflictWoundsEventArgs).SenderId = 0;
      ((GameEventArgs)inflictWoundsEventArgs).EventId = (string)null;
      ((GameEventArgs)inflictWoundsEventArgs).EventType = (EventType)0;
      ((GameEventArgs)inflictWoundsEventArgs).NeedResponse = false;
      string[] ss = new string[0];
      this.PopulateWithArgs(inflictWoundsEventArgs, ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(InflictWoundsEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException819()
{
    try
    {
      InflictWoundsEventArgs inflictWoundsEventArgs;
      inflictWoundsEventArgs = new InflictWoundsEventArgs(0, 0, 0, 0);
      ((GameEventArgs)inflictWoundsEventArgs).SenderId = 0;
      ((GameEventArgs)inflictWoundsEventArgs).EventId = (string)null;
      ((GameEventArgs)inflictWoundsEventArgs).EventType = (EventType)0;
      ((GameEventArgs)inflictWoundsEventArgs).NeedResponse = false;
      this.PopulateWithArgs(inflictWoundsEventArgs, (string[])null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
    }
}
