// <copyright file="InventoryFieldEventArgsTest.Constructor01.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;

namespace Descent.Messaging.Events
{
    public partial class InventoryFieldEventArgsTest
    {
[TestMethod]
[PexGeneratedBy(typeof(InventoryFieldEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException369()
{
    try
    {
      InventoryFieldEventArgs inventoryFieldEventArgs;
      string[] ss = new string[1];
      ss[0] = "-9\0";
      inventoryFieldEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(InventoryFieldEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException72()
{
    try
    {
      InventoryFieldEventArgs inventoryFieldEventArgs;
      string[] ss = new string[1];
      ss[0] = "-0\u0001";
      inventoryFieldEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(InventoryFieldEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException838()
{
    try
    {
      InventoryFieldEventArgs inventoryFieldEventArgs;
      string[] ss = new string[1];
      ss[0] = "-9";
      inventoryFieldEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(InventoryFieldEventArgsTest))]
public void Constructor01777()
{
    InventoryFieldEventArgs inventoryFieldEventArgs;
    string[] ss = new string[1];
    ss[0] = "0";
    inventoryFieldEventArgs = this.Constructor01(ss);
    Assert.IsNotNull((object)inventoryFieldEventArgs);
    Assert.AreEqual<int>(0, inventoryFieldEventArgs.EquipmentId);
    Assert.AreEqual<int>(0, inventoryFieldEventArgs.InventoryField);
    Assert.AreEqual<int>(0, ((GameEventArgs)inventoryFieldEventArgs).SenderId);
    Assert.AreEqual<string>
        ((string)null, ((GameEventArgs)inventoryFieldEventArgs).EventId);
    Assert.AreEqual<EventType>
        ((EventType)0, ((GameEventArgs)inventoryFieldEventArgs).EventType);
    Assert.AreEqual<bool>
        (false, ((GameEventArgs)inventoryFieldEventArgs).NeedResponse);
}
[TestMethod]
[PexGeneratedBy(typeof(InventoryFieldEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException998()
{
    try
    {
      InventoryFieldEventArgs inventoryFieldEventArgs;
      string[] ss = new string[1];
      ss[0] = "-\0";
      inventoryFieldEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(InventoryFieldEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException744()
{
    try
    {
      InventoryFieldEventArgs inventoryFieldEventArgs;
      string[] ss = new string[1];
      ss[0] = ":";
      inventoryFieldEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(InventoryFieldEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException140()
{
    try
    {
      InventoryFieldEventArgs inventoryFieldEventArgs;
      string[] ss = new string[1];
      ss[0] = "-";
      inventoryFieldEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(InventoryFieldEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException754()
{
    try
    {
      InventoryFieldEventArgs inventoryFieldEventArgs;
      string[] ss = new string[1];
      ss[0] = "\u0001";
      inventoryFieldEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(InventoryFieldEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException339()
{
    try
    {
      InventoryFieldEventArgs inventoryFieldEventArgs;
      string[] ss = new string[1];
      ss[0] = "\0";
      inventoryFieldEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(InventoryFieldEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException668()
{
    try
    {
      InventoryFieldEventArgs inventoryFieldEventArgs;
      string[] ss = new string[1];
      ss[0] = "";
      inventoryFieldEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(InventoryFieldEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException336()
{
    try
    {
      InventoryFieldEventArgs inventoryFieldEventArgs;
      string[] ss = new string[1];
      inventoryFieldEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(InventoryFieldEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException828()
{
    try
    {
      InventoryFieldEventArgs inventoryFieldEventArgs;
      string[] ss = new string[0];
      inventoryFieldEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(InventoryFieldEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException888()
{
    try
    {
      InventoryFieldEventArgs inventoryFieldEventArgs;
      inventoryFieldEventArgs = this.Constructor01((string[])null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(InventoryFieldEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void ConstructorThrowsContractException261()
{
    try
    {
      InventoryFieldEventArgs inventoryFieldEventArgs;
      inventoryFieldEventArgs = this.Constructor(int.MinValue);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(InventoryFieldEventArgsTest))]
public void Constructor328()
{
    InventoryFieldEventArgs inventoryFieldEventArgs;
    inventoryFieldEventArgs = this.Constructor(0);
    Assert.IsNotNull((object)inventoryFieldEventArgs);
    Assert.AreEqual<int>(0, inventoryFieldEventArgs.EquipmentId);
    Assert.AreEqual<int>(0, inventoryFieldEventArgs.InventoryField);
    Assert.AreEqual<int>(0, ((GameEventArgs)inventoryFieldEventArgs).SenderId);
    Assert.AreEqual<string>
        ((string)null, ((GameEventArgs)inventoryFieldEventArgs).EventId);
    Assert.AreEqual<EventType>
        ((EventType)0, ((GameEventArgs)inventoryFieldEventArgs).EventType);
    Assert.AreEqual<bool>
        (false, ((GameEventArgs)inventoryFieldEventArgs).NeedResponse);
}
    }
}
