// <copyright file="PlayerJoinedEventArgsTest.ToString01.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Descent.Messaging.Events
{
    public partial class PlayerJoinedEventArgsTest
    {
[TestMethod]
[PexGeneratedBy(typeof(PlayerJoinedEventArgsTest))]
public void ToString0198()
{
    PlayerJoinedEventArgs playerJoinedEventArgs;
    string s;
    playerJoinedEventArgs = new PlayerJoinedEventArgs(1, "");
    ((GameEventArgs)playerJoinedEventArgs).SenderId = 0;
    ((GameEventArgs)playerJoinedEventArgs).EventId = (string)null;
    ((GameEventArgs)playerJoinedEventArgs).EventType = (EventType)0;
    ((GameEventArgs)playerJoinedEventArgs).NeedResponse = false;
    s = this.ToString01(playerJoinedEventArgs);
    Assert.AreEqual<string>("1,", s);
    Assert.IsNotNull((object)playerJoinedEventArgs);
    Assert.AreEqual<int>(1, playerJoinedEventArgs.PlayerId);
    Assert.AreEqual<string>("", playerJoinedEventArgs.PlayerNick);
    Assert.AreEqual<int>(0, ((GameEventArgs)playerJoinedEventArgs).SenderId);
    Assert.AreEqual<string>
        ((string)null, ((GameEventArgs)playerJoinedEventArgs).EventId);
    Assert.AreEqual<EventType>
        ((EventType)0, ((GameEventArgs)playerJoinedEventArgs).EventType);
    Assert.AreEqual<bool>
        (false, ((GameEventArgs)playerJoinedEventArgs).NeedResponse);
}
    }
}
