// <copyright file="RequestBuyEquipmentEventArgsTest.Constructor01.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;

namespace Descent.Messaging.Events
{
    public partial class RequestBuyEquipmentEventArgsTest
    {
[TestMethod]
[PexGeneratedBy(typeof(RequestBuyEquipmentEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException741()
{
    try
    {
      RequestBuyEquipmentEventArgs requestBuyEquipmentEventArgs;
      string[] ss = new string[1];
      ss[0] = "00:";
      requestBuyEquipmentEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(RequestBuyEquipmentEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException882()
{
    try
    {
      RequestBuyEquipmentEventArgs requestBuyEquipmentEventArgs;
      string[] ss = new string[1];
      ss[0] = "-0:";
      requestBuyEquipmentEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(RequestBuyEquipmentEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException561()
{
    try
    {
      RequestBuyEquipmentEventArgs requestBuyEquipmentEventArgs;
      string[] ss = new string[1];
      ss[0] = "-\0";
      requestBuyEquipmentEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(RequestBuyEquipmentEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException420()
{
    try
    {
      RequestBuyEquipmentEventArgs requestBuyEquipmentEventArgs;
      string[] ss = new string[1];
      ss[0] = ":";
      requestBuyEquipmentEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(RequestBuyEquipmentEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException727()
{
    try
    {
      RequestBuyEquipmentEventArgs requestBuyEquipmentEventArgs;
      string[] ss = new string[1];
      ss[0] = "-";
      requestBuyEquipmentEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(RequestBuyEquipmentEventArgsTest))]
public void Constructor01819()
{
    RequestBuyEquipmentEventArgs requestBuyEquipmentEventArgs;
    string[] ss = new string[1];
    ss[0] = "0";
    requestBuyEquipmentEventArgs = this.Constructor01(ss);
    Assert.IsNotNull((object)requestBuyEquipmentEventArgs);
    Assert.AreEqual<int>(0, requestBuyEquipmentEventArgs.EquipmentId);
    Assert.AreEqual<int>(0, ((GameEventArgs)requestBuyEquipmentEventArgs).SenderId);
    Assert.AreEqual<string>
        ((string)null, ((GameEventArgs)requestBuyEquipmentEventArgs).EventId);
    Assert.AreEqual<EventType>
        ((EventType)0, ((GameEventArgs)requestBuyEquipmentEventArgs).EventType);
    Assert.AreEqual<bool>
        (false, ((GameEventArgs)requestBuyEquipmentEventArgs).NeedResponse);
}
[TestMethod]
[PexGeneratedBy(typeof(RequestBuyEquipmentEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException945()
{
    try
    {
      RequestBuyEquipmentEventArgs requestBuyEquipmentEventArgs;
      string[] ss = new string[1];
      ss[0] = "\u0001";
      requestBuyEquipmentEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(RequestBuyEquipmentEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException776()
{
    try
    {
      RequestBuyEquipmentEventArgs requestBuyEquipmentEventArgs;
      string[] ss = new string[1];
      ss[0] = "\0";
      requestBuyEquipmentEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(RequestBuyEquipmentEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException838()
{
    try
    {
      RequestBuyEquipmentEventArgs requestBuyEquipmentEventArgs;
      string[] ss = new string[1];
      ss[0] = "";
      requestBuyEquipmentEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(RequestBuyEquipmentEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException29()
{
    try
    {
      RequestBuyEquipmentEventArgs requestBuyEquipmentEventArgs;
      string[] ss = new string[1];
      requestBuyEquipmentEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(RequestBuyEquipmentEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException543()
{
    try
    {
      RequestBuyEquipmentEventArgs requestBuyEquipmentEventArgs;
      string[] ss = new string[0];
      requestBuyEquipmentEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(RequestBuyEquipmentEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException504()
{
    try
    {
      RequestBuyEquipmentEventArgs requestBuyEquipmentEventArgs;
      requestBuyEquipmentEventArgs = this.Constructor01((string[])null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(RequestBuyEquipmentEventArgsTest))]
public void Constructor599()
{
    RequestBuyEquipmentEventArgs requestBuyEquipmentEventArgs;
    requestBuyEquipmentEventArgs = this.Constructor(1);
    Assert.IsNotNull((object)requestBuyEquipmentEventArgs);
    Assert.AreEqual<int>(1, requestBuyEquipmentEventArgs.EquipmentId);
    Assert.AreEqual<int>(0, ((GameEventArgs)requestBuyEquipmentEventArgs).SenderId);
    Assert.AreEqual<string>
        ((string)null, ((GameEventArgs)requestBuyEquipmentEventArgs).EventId);
    Assert.AreEqual<EventType>
        ((EventType)0, ((GameEventArgs)requestBuyEquipmentEventArgs).EventType);
    Assert.AreEqual<bool>
        (false, ((GameEventArgs)requestBuyEquipmentEventArgs).NeedResponse);
}
[TestMethod]
[PexGeneratedBy(typeof(RequestBuyEquipmentEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void ConstructorThrowsContractException919()
{
    try
    {
      RequestBuyEquipmentEventArgs requestBuyEquipmentEventArgs;
      requestBuyEquipmentEventArgs = this.Constructor(0);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
    }
}
