// <copyright file="SurgeAbilityEventArgsTest.Constructor01.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;

namespace Descent.Messaging.Events
{
    public partial class SurgeAbilityEventArgsTest
    {
[TestMethod]
[PexGeneratedBy(typeof(SurgeAbilityEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException206()
{
    try
    {
      SurgeAbilityEventArgs surgeAbilityEventArgs;
      string[] ss = new string[1];
      ss[0] = "00:";
      surgeAbilityEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(SurgeAbilityEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException11()
{
    try
    {
      SurgeAbilityEventArgs surgeAbilityEventArgs;
      string[] ss = new string[1];
      ss[0] = "-0:";
      surgeAbilityEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(SurgeAbilityEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException500()
{
    try
    {
      SurgeAbilityEventArgs surgeAbilityEventArgs;
      string[] ss = new string[1];
      ss[0] = "-\0";
      surgeAbilityEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(SurgeAbilityEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException310()
{
    try
    {
      SurgeAbilityEventArgs surgeAbilityEventArgs;
      string[] ss = new string[1];
      ss[0] = ":";
      surgeAbilityEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(SurgeAbilityEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException839()
{
    try
    {
      SurgeAbilityEventArgs surgeAbilityEventArgs;
      string[] ss = new string[1];
      ss[0] = "-";
      surgeAbilityEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(SurgeAbilityEventArgsTest))]
public void Constructor0134()
{
    SurgeAbilityEventArgs surgeAbilityEventArgs;
    string[] ss = new string[1];
    ss[0] = "0";
    surgeAbilityEventArgs = this.Constructor01(ss);
    Assert.IsNotNull((object)surgeAbilityEventArgs);
    Assert.AreEqual<int>(0, surgeAbilityEventArgs.AbilityId);
    Assert.AreEqual<int>(0, ((GameEventArgs)surgeAbilityEventArgs).SenderId);
    Assert.AreEqual<string>
        ((string)null, ((GameEventArgs)surgeAbilityEventArgs).EventId);
    Assert.AreEqual<EventType>
        ((EventType)0, ((GameEventArgs)surgeAbilityEventArgs).EventType);
    Assert.AreEqual<bool>
        (false, ((GameEventArgs)surgeAbilityEventArgs).NeedResponse);
}
[TestMethod]
[PexGeneratedBy(typeof(SurgeAbilityEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException403()
{
    try
    {
      SurgeAbilityEventArgs surgeAbilityEventArgs;
      string[] ss = new string[1];
      ss[0] = "\u0001";
      surgeAbilityEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(SurgeAbilityEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException249()
{
    try
    {
      SurgeAbilityEventArgs surgeAbilityEventArgs;
      string[] ss = new string[1];
      ss[0] = "\0";
      surgeAbilityEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(SurgeAbilityEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException266()
{
    try
    {
      SurgeAbilityEventArgs surgeAbilityEventArgs;
      string[] ss = new string[1];
      ss[0] = "";
      surgeAbilityEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(SurgeAbilityEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException595()
{
    try
    {
      SurgeAbilityEventArgs surgeAbilityEventArgs;
      string[] ss = new string[1];
      surgeAbilityEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(SurgeAbilityEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException865()
{
    try
    {
      SurgeAbilityEventArgs surgeAbilityEventArgs;
      string[] ss = new string[0];
      surgeAbilityEventArgs = this.Constructor01(ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(SurgeAbilityEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void Constructor01ThrowsContractException136()
{
    try
    {
      SurgeAbilityEventArgs surgeAbilityEventArgs;
      surgeAbilityEventArgs = this.Constructor01((string[])null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(SurgeAbilityEventArgsTest))]
public void Constructor601()
{
    SurgeAbilityEventArgs surgeAbilityEventArgs;
    surgeAbilityEventArgs = this.Constructor(2);
    Assert.IsNotNull((object)surgeAbilityEventArgs);
    Assert.AreEqual<int>(2, surgeAbilityEventArgs.AbilityId);
    Assert.AreEqual<int>(0, ((GameEventArgs)surgeAbilityEventArgs).SenderId);
    Assert.AreEqual<string>
        ((string)null, ((GameEventArgs)surgeAbilityEventArgs).EventId);
    Assert.AreEqual<EventType>
        ((EventType)0, ((GameEventArgs)surgeAbilityEventArgs).EventType);
    Assert.AreEqual<bool>
        (false, ((GameEventArgs)surgeAbilityEventArgs).NeedResponse);
}
[TestMethod]
[PexGeneratedBy(typeof(SurgeAbilityEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void ConstructorThrowsContractException651()
{
    try
    {
      SurgeAbilityEventArgs surgeAbilityEventArgs;
      surgeAbilityEventArgs = this.Constructor(0);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
    }
}
