// <copyright file="SwitchItemsEventArgsTest.ToString01.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Descent.Messaging.Events
{
    public partial class SwitchItemsEventArgsTest
    {
[TestMethod]
[PexGeneratedBy(typeof(SwitchItemsEventArgsTest))]
public void ToString01145()
{
    SwitchItemsEventArgs switchItemsEventArgs;
    string s;
    switchItemsEventArgs = new SwitchItemsEventArgs(1, 0);
    ((GameEventArgs)switchItemsEventArgs).SenderId = 0;
    ((GameEventArgs)switchItemsEventArgs).EventId = (string)null;
    ((GameEventArgs)switchItemsEventArgs).EventType = (EventType)0;
    ((GameEventArgs)switchItemsEventArgs).NeedResponse = false;
    s = this.ToString01(switchItemsEventArgs);
    Assert.AreEqual<string>("1,0", s);
    Assert.IsNotNull((object)switchItemsEventArgs);
    Assert.AreEqual<int>(1, switchItemsEventArgs.Field1);
    Assert.AreEqual<int>(0, switchItemsEventArgs.Field2);
    Assert.AreEqual<int>(0, ((GameEventArgs)switchItemsEventArgs).SenderId);
    Assert.AreEqual<string>
        ((string)null, ((GameEventArgs)switchItemsEventArgs).EventId);
    Assert.AreEqual<EventType>
        ((EventType)0, ((GameEventArgs)switchItemsEventArgs).EventType);
    Assert.AreEqual<bool>(false, ((GameEventArgs)switchItemsEventArgs).NeedResponse);
}
[TestMethod]
[PexGeneratedBy(typeof(SwitchItemsEventArgsTest))]
public void ToString01413()
{
    SwitchItemsEventArgs switchItemsEventArgs;
    string s;
    switchItemsEventArgs = new SwitchItemsEventArgs(0, 0);
    ((GameEventArgs)switchItemsEventArgs).SenderId = 0;
    ((GameEventArgs)switchItemsEventArgs).EventId = (string)null;
    ((GameEventArgs)switchItemsEventArgs).EventType = (EventType)0;
    ((GameEventArgs)switchItemsEventArgs).NeedResponse = false;
    s = this.ToString01(switchItemsEventArgs);
    Assert.AreEqual<string>("0,0", s);
    Assert.IsNotNull((object)switchItemsEventArgs);
    Assert.AreEqual<int>(0, switchItemsEventArgs.Field1);
    Assert.AreEqual<int>(0, switchItemsEventArgs.Field2);
    Assert.AreEqual<int>(0, ((GameEventArgs)switchItemsEventArgs).SenderId);
    Assert.AreEqual<string>
        ((string)null, ((GameEventArgs)switchItemsEventArgs).EventId);
    Assert.AreEqual<EventType>
        ((EventType)0, ((GameEventArgs)switchItemsEventArgs).EventType);
    Assert.AreEqual<bool>(false, ((GameEventArgs)switchItemsEventArgs).NeedResponse);
}
    }
}
