// <copyright file="TreasureEventArgsTest.PopulateWithArgs.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;

namespace Descent.Messaging.Events
{
    public partial class TreasureEventArgsTest
    {
[TestMethod]
[PexGeneratedBy(typeof(TreasureEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException612()
{
    try
    {
      TreasureEventArgs treasureEventArgs;
      treasureEventArgs = new TreasureEventArgs(1);
      ((GameEventArgs)treasureEventArgs).SenderId = 0;
      ((GameEventArgs)treasureEventArgs).EventId = (string)null;
      ((GameEventArgs)treasureEventArgs).EventType = (EventType)0;
      ((GameEventArgs)treasureEventArgs).NeedResponse = false;
      string[] ss = new string[1];
      ss[0] = "-00:";
      this.PopulateWithArgs(treasureEventArgs, ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(TreasureEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException672()
{
    try
    {
      TreasureEventArgs treasureEventArgs;
      treasureEventArgs = new TreasureEventArgs(1);
      ((GameEventArgs)treasureEventArgs).SenderId = 0;
      ((GameEventArgs)treasureEventArgs).EventId = (string)null;
      ((GameEventArgs)treasureEventArgs).EventType = (EventType)0;
      ((GameEventArgs)treasureEventArgs).NeedResponse = false;
      string[] ss = new string[1];
      ss[0] = "-0:";
      this.PopulateWithArgs(treasureEventArgs, ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(TreasureEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException396()
{
    try
    {
      TreasureEventArgs treasureEventArgs;
      treasureEventArgs = new TreasureEventArgs(1);
      ((GameEventArgs)treasureEventArgs).SenderId = 0;
      ((GameEventArgs)treasureEventArgs).EventId = (string)null;
      ((GameEventArgs)treasureEventArgs).EventType = (EventType)0;
      ((GameEventArgs)treasureEventArgs).NeedResponse = false;
      string[] ss = new string[1];
      ss[0] = "-\0";
      this.PopulateWithArgs(treasureEventArgs, ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(TreasureEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException218()
{
    try
    {
      TreasureEventArgs treasureEventArgs;
      treasureEventArgs = new TreasureEventArgs(1);
      ((GameEventArgs)treasureEventArgs).SenderId = 0;
      ((GameEventArgs)treasureEventArgs).EventId = (string)null;
      ((GameEventArgs)treasureEventArgs).EventType = (EventType)0;
      ((GameEventArgs)treasureEventArgs).NeedResponse = false;
      string[] ss = new string[1];
      ss[0] = "-";
      this.PopulateWithArgs(treasureEventArgs, ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(TreasureEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException339()
{
    try
    {
      TreasureEventArgs treasureEventArgs;
      treasureEventArgs = new TreasureEventArgs(1);
      ((GameEventArgs)treasureEventArgs).SenderId = 0;
      ((GameEventArgs)treasureEventArgs).EventId = (string)null;
      ((GameEventArgs)treasureEventArgs).EventType = (EventType)0;
      ((GameEventArgs)treasureEventArgs).NeedResponse = false;
      string[] ss = new string[1];
      ss[0] = ":";
      this.PopulateWithArgs(treasureEventArgs, ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(TreasureEventArgsTest))]
public void PopulateWithArgs980()
{
    TreasureEventArgs treasureEventArgs;
    treasureEventArgs = new TreasureEventArgs(1);
    ((GameEventArgs)treasureEventArgs).SenderId = 0;
    ((GameEventArgs)treasureEventArgs).EventId = (string)null;
    ((GameEventArgs)treasureEventArgs).EventType = (EventType)0;
    ((GameEventArgs)treasureEventArgs).NeedResponse = false;
    string[] ss = new string[1];
    ss[0] = "0";
    this.PopulateWithArgs(treasureEventArgs, ss);
    Assert.IsNotNull((object)treasureEventArgs);
    Assert.AreEqual<int>(0, treasureEventArgs.TreasureId);
    Assert.AreEqual<int>(0, ((GameEventArgs)treasureEventArgs).SenderId);
    Assert.AreEqual<string>
        ((string)null, ((GameEventArgs)treasureEventArgs).EventId);
    Assert.AreEqual<EventType>
        ((EventType)0, ((GameEventArgs)treasureEventArgs).EventType);
    Assert.AreEqual<bool>(false, ((GameEventArgs)treasureEventArgs).NeedResponse);
}
[TestMethod]
[PexGeneratedBy(typeof(TreasureEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException895()
{
    try
    {
      TreasureEventArgs treasureEventArgs;
      treasureEventArgs = new TreasureEventArgs(1);
      ((GameEventArgs)treasureEventArgs).SenderId = 0;
      ((GameEventArgs)treasureEventArgs).EventId = (string)null;
      ((GameEventArgs)treasureEventArgs).EventType = (EventType)0;
      ((GameEventArgs)treasureEventArgs).NeedResponse = false;
      string[] ss = new string[1];
      ss[0] = "\0";
      this.PopulateWithArgs(treasureEventArgs, ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(TreasureEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException801()
{
    try
    {
      TreasureEventArgs treasureEventArgs;
      treasureEventArgs = new TreasureEventArgs(1);
      ((GameEventArgs)treasureEventArgs).SenderId = 0;
      ((GameEventArgs)treasureEventArgs).EventId = (string)null;
      ((GameEventArgs)treasureEventArgs).EventType = (EventType)0;
      ((GameEventArgs)treasureEventArgs).NeedResponse = false;
      string[] ss = new string[1];
      ss[0] = "";
      this.PopulateWithArgs(treasureEventArgs, ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(TreasureEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException717()
{
    try
    {
      TreasureEventArgs treasureEventArgs;
      treasureEventArgs = new TreasureEventArgs(1);
      ((GameEventArgs)treasureEventArgs).SenderId = 0;
      ((GameEventArgs)treasureEventArgs).EventId = (string)null;
      ((GameEventArgs)treasureEventArgs).EventType = (EventType)0;
      ((GameEventArgs)treasureEventArgs).NeedResponse = false;
      string[] ss = new string[1];
      this.PopulateWithArgs(treasureEventArgs, ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(TreasureEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException478()
{
    try
    {
      TreasureEventArgs treasureEventArgs;
      treasureEventArgs = new TreasureEventArgs(1);
      ((GameEventArgs)treasureEventArgs).SenderId = 0;
      ((GameEventArgs)treasureEventArgs).EventId = (string)null;
      ((GameEventArgs)treasureEventArgs).EventType = (EventType)0;
      ((GameEventArgs)treasureEventArgs).NeedResponse = false;
      string[] ss = new string[0];
      this.PopulateWithArgs(treasureEventArgs, ss);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(TreasureEventArgsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PopulateWithArgsThrowsContractException223()
{
    try
    {
      TreasureEventArgs treasureEventArgs;
      treasureEventArgs = new TreasureEventArgs(1);
      ((GameEventArgs)treasureEventArgs).SenderId = 0;
      ((GameEventArgs)treasureEventArgs).EventId = (string)null;
      ((GameEventArgs)treasureEventArgs).EventType = (EventType)0;
      ((GameEventArgs)treasureEventArgs).NeedResponse = false;
      this.PopulateWithArgs(treasureEventArgs, (string[])null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
    }
}
